ALTER TABLE communications ADD COLUMN IF NOT EXISTS classification VARCHAR(50) DEFAULT 'UNKNOWN' COMMENT 'JUDICIAL, NON_JUDICIAL, UNKNOWN';
ALTER TABLE communications ADD COLUMN IF NOT EXISTS cnj_number VARCHAR(50) DEFAULT NULL COMMENT 'Número de autos CNJ';
ALTER TABLE communications ADD COLUMN IF NOT EXISTS vara VARCHAR(255) DEFAULT NULL;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS comarca VARCHAR(255) DEFAULT NULL;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS has_complete_data BOOLEAN DEFAULT FALSE COMMENT 'Has CNJ, vara, comarca';
