object fRelCapa: TfRelCapa
  Left = 192
  Top = 311
  Caption = 'Relat'#243'rio da Capa'
  ClientHeight = 717
  ClientWidth = 1264
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Scaled = False
  TextHeight = 13
  object QuickRep1: TRLReport
    Tag = 1
    Left = 80
    Top = -40
    Width = 1123
    Height = 794
    Margins.LeftMargin = 25.000000000000000000
    DataSource = fProcessos.ds_ParcelasCapa
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    PageSetup.Orientation = poLandscape
    object QRBand1: TRLBand
      Left = 94
      Top = 38
      Width = 991
      Height = 659
      object QRDBText1: TRLDBText
        Left = 448
        Top = 15
        Width = 519
        Height = 89
        Alignment = taRightJustify
        DataField = 'PRO_NPERC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -80
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText3: TRLDBText
        Left = 59
        Top = 275
        Width = 133
        Height = 27
        DataField = 'VAR_DESC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText4: TRLDBText
        Left = 127
        Top = 235
        Width = 141
        Height = 27
        DataField = 'COM_DESC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText5: TRLDBText
        Left = 743
        Top = 120
        Width = 222
        Height = 36
        Alignment = taRightJustify
        DataField = 'CAS_CODIGO'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -32
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText6: TRLDBText
        Left = 124
        Top = 472
        Width = 125
        Height = 22
        DataField = 'PRO_DCOLE'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText7: TRLDBText
        Left = 87
        Top = 323
        Width = 160
        Height = 32
        DataField = 'LCO_NOME'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -27
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText8: TRLDBText
        Left = 143
        Top = 380
        Width = 64
        Height = 15
        DataField = 'LCO_CATE'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText9: TRLDBText
        Left = 201
        Top = 502
        Width = 113
        Height = 22
        DataField = 'PRO_DREC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRLabel1: TRLLabel
        Left = 8
        Top = 329
        Width = 74
        Height = 21
        Caption = 'Coletador:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel2: TRLLabel
        Left = 8
        Top = 377
        Width = 131
        Height = 21
        Caption = 'Tipo do Coletador:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel3: TRLLabel
        Left = 8
        Top = 473
        Width = 111
        Height = 21
        Caption = 'Data da Coleta:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel4: TRLLabel
        Left = 8
        Top = 504
        Width = 188
        Height = 28
        Caption = 'Data e Hora da Recep'#231#227'o:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel5: TRLLabel
        Left = 8
        Top = 257
        Width = 43
        Height = 21
        Caption = 'Local:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel6: TRLLabel
        Left = 524
        Top = 543
        Width = 156
        Height = 21
        Caption = 'Data Limite do Laudo:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object DataLimite: TRLLabel
        Left = 698
        Top = 540
        Width = 102
        Height = 25
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -21
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel7: TRLLabel
        Left = 8
        Top = 543
        Width = 120
        Height = 21
        Caption = 'Quem cadastrou:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object Cadastrador: TRLLabel
        Left = 134
        Top = 543
        Width = 89
        Height = 21
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel8: TRLLabel
        Left = 8
        Top = 634
        Width = 105
        Height = 19
        Caption = 'Valores Pagos'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object CRIANCA: TRLLabel
        Left = 71
        Top = 418
        Width = 102
        Height = 34
        Caption = 'Crianca'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -29
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel9: TRLLabel
        Left = 8
        Top = 425
        Width = 60
        Height = 21
        Caption = 'Crian'#231'a:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel10: TRLLabel
        Left = 134
        Top = 586
        Width = 177
        Height = 41
        Caption = 'INCLUS'#195'O'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -35
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel11: TRLLabel
        Left = 421
        Top = 587
        Width = 189
        Height = 41
        Caption = 'EXCLUS'#195'O'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -35
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel12: TRLLabel
        Left = 708
        Top = 587
        Width = 263
        Height = 41
        Caption = 'INCONCLUSIVO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -35
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object Hora: TRLLabel
        Left = 317
        Top = 503
        Width = 26
        Height = 23
        AutoSize = False
        Caption = 'HORA'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object MINUTO: TRLLabel
        Left = 351
        Top = 503
        Width = 24
        Height = 23
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel13: TRLLabel
        Left = 110
        Top = 238
        Width = 6
        Height = 21
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel14: TRLLabel
        Left = 305
        Top = 503
        Width = 6
        Height = 21
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel15: TRLLabel
        Left = 233
        Top = 472
        Width = 6
        Height = 21
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object HORACOL: TRLLabel
        Left = 246
        Top = 472
        Width = 25
        Height = 23
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object MINUTOCOL: TRLLabel
        Left = 282
        Top = 472
        Width = 24
        Height = 23
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel16: TRLLabel
        Left = 355
        Top = 563
        Width = 40
        Height = 17
        Caption = 'rubrica'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel18: TRLLabel
        Left = 269
        Top = 472
        Width = 11
        Height = 23
        Caption = 'h'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel19: TRLLabel
        Left = 304
        Top = 472
        Width = 31
        Height = 23
        Caption = 'min'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel20: TRLLabel
        Left = 372
        Top = 503
        Width = 31
        Height = 23
        Caption = 'min'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel21: TRLLabel
        Left = 339
        Top = 503
        Width = 11
        Height = 23
        Caption = 'h'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel17: TRLLabel
        Left = 668
        Top = 219
        Width = 129
        Height = 21
        Caption = 'OBSERVA'#199#213'ES:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object NumLaudo: TRLLabel
        Left = 30
        Top = 121
        Width = 156
        Height = 37
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -32
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel22: TRLLabel
        Left = 668
        Top = 219
        Width = 129
        Height = 21
        Caption = 'OBSERVA'#199#213'ES:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel23: TRLLabel
        Left = 668
        Top = 432
        Width = 185
        Height = 21
        Caption = 'Envio: ____ / _____ / 20 ___'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel24: TRLLabel
        Left = 668
        Top = 456
        Width = 118
        Height = 17
        Caption = 'Meio: (    ) E-MAIL'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel25: TRLLabel
        Left = 706
        Top = 477
        Width = 128
        Height = 21
        Caption = '(    ) PROTOCOLO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object ESTADO: TRLLabel
        Left = 59
        Top = 234
        Width = 45
        Height = 28
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel27: TRLLabel
        Left = 432
        Top = 219
        Width = 205
        Height = 23
        Caption = 'NOTA FICAL: ___________'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -17
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel28: TRLLabel
        Left = 432
        Top = 259
        Width = 101
        Height = 23
        Caption = 'DIGITAL: (   )'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -17
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel30: TRLLabel
        Left = 706
        Top = 497
        Width = 169
        Height = 21
        Caption = '(    ) CORREIO ________'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel31: TRLLabel
        Left = 706
        Top = 518
        Width = 228
        Height = 21
        Caption = '(    ) PROTOCOLO ELETR'#212'NICO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel26: TRLLabel
        Left = 832
        Top = 635
        Width = 140
        Height = 23
        Caption = 'ESCANEADO: (   )'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -17
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel29: TRLLabel
        Left = 12
        Top = 188
        Width = 45
        Height = 21
        Caption = 'Autos:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRDBText13: TRLDBText
        Left = 62
        Top = 186
        Width = 107
        Height = 23
        DataField = 'PRO_AUTO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object BarraCodigo: TRLBarcode
        Left = 48
        Top = 70
        Width = 125
        Height = 34
        Margins.LeftMargin = 1.000000000000000000
        Margins.RightMargin = 1.000000000000000000
        Alignment = taCenter
        BarcodeType = bcCode128A
      end
      object RLLabel1: TRLLabel
        Left = 579
        Top = 259
        Width = 179
        Height = 19
        Caption = 'CERTIFICADO: ______'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -17
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
    end
    object QRBand2: TRLBand
      Left = 94
      Top = 697
      Width = 991
      Height = 20
      object QRDBText11: TRLDBText
        Left = 150
        Top = 1
        Width = 63
        Height = 16
        Alignment = taRightJustify
        DataField = 'PAR_VLR'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText12: TRLDBText
        Left = 237
        Top = 1
        Width = 73
        Height = 16
        DataField = 'PAR_TPPG'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText10: TRLDBText
        Left = 533
        Top = 1
        Width = 452
        Height = 17
        AutoSize = False
        DataField = 'PAR_OBS'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText2: TRLDBText
        Left = 28
        Top = 1
        Width = 72
        Height = 16
        Alignment = taCenter
        DataField = 'PAR_DATA'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
    end
  end
end
