
SET SQL DIALECT 3; 

/* CREATE DATABASE 'C:\SCPG\Base\SGBD_SCPG.fdb' PAGE_SIZE 4096 DEFAULT CHARACTER SET NONE */


/*  Generators or sequences */
CREATE GENERATOR GEN_PESSOAS_COD;
CREATE GENERATOR GEN_TB_ALELOS_ID;
CREATE GENERATOR GEN_TB_ALELOS_TIPOS_ID;
CREATE GENERATOR GEN_TB_ALELOS_TMP_ID;
CREATE GENERATOR GEN_TB_AUDITORIA_ID;
CREATE GENERATOR GEN_TB_COLETA_ADICIONAL_ID;
CREATE GENERATOR GEN_TB_CREDITOS_ID;
CREATE GENERATOR GEN_TB_ENDERECOS_ID;
CREATE GENERATOR GEN_TB_EXTRACAO_CASOS_ID;
CREATE GENERATOR GEN_TB_EXTRACAO_ID;
CREATE GENERATOR GEN_TB_HISTORICO_ID;
CREATE GENERATOR GEN_TB_IMPRESSOES_ID;
CREATE GENERATOR GEN_TB_KITS_ID;
CREATE GENERATOR GEN_TB_PARCELAS_ID;
CREATE GENERATOR GEN_TB_PESQUISA_ID;
CREATE GENERATOR GEN_TB_PROCED_CARGA_ID;
CREATE GENERATOR GEN_TB_PROCED_RESULTADO_ID;
CREATE GENERATOR GRID_LINHAS;
CREATE GENERATOR IBE$LOG_TABLES_GEN;
CREATE GENERATOR IBE$VERSION_HISTORY_ID_GEN;


/* Table: IBE$LOG_BLOB_FIELDS, Owner: SYSDBA */
CREATE TABLE IBE$LOG_BLOB_FIELDS (LOG_TABLES_ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(67) CHARACTER SET UNICODE_FSS NOT NULL,
        OLD_CHAR_VALUE VARCHAR(10000) CHARACTER SET UNICODE_FSS,
        NEW_CHAR_VALUE VARCHAR(10000) CHARACTER SET UNICODE_FSS,
        OLD_BLOB_VALUE BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        NEW_BLOB_VALUE BLOB SUB_TYPE 0 SEGMENT SIZE 80);

/* Table: IBE$LOG_FIELDS, Owner: SYSDBA */
CREATE TABLE IBE$LOG_FIELDS (LOG_TABLES_ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(67) CHARACTER SET UNICODE_FSS NOT NULL,
        OLD_VALUE VARCHAR(255) CHARACTER SET UNICODE_FSS,
        NEW_VALUE VARCHAR(255) CHARACTER SET UNICODE_FSS);

/* Table: IBE$LOG_KEYS, Owner: SYSDBA */
CREATE TABLE IBE$LOG_KEYS (LOG_TABLES_ID NUMERIC(18, 0) NOT NULL,
        KEY_FIELD VARCHAR(67) CHARACTER SET UNICODE_FSS NOT NULL,
        KEY_VALUE VARCHAR(255) CHARACTER SET UNICODE_FSS);

/* Table: IBE$LOG_TABLES, Owner: SYSDBA */
CREATE TABLE IBE$LOG_TABLES (ID NUMERIC(18, 0) NOT NULL,
        TABLE_NAME VARCHAR(67) CHARACTER SET UNICODE_FSS NOT NULL,
        OPERATION VARCHAR(1) NOT NULL,
        DATE_TIME TIMESTAMP NOT NULL,
        USER_NAME VARCHAR(67) NOT NULL,
PRIMARY KEY (ID));

/* Table: IBE$VERSION_HISTORY, Owner: SYSDBA */
CREATE TABLE IBE$VERSION_HISTORY (IBE$VH_ID INTEGER NOT NULL,
        IBE$VH_MODIFY_DATE TIMESTAMP NOT NULL,
        IBE$VH_USER_NAME VARCHAR(67),
        IBE$VH_OBJECT_TYPE SMALLINT NOT NULL,
        IBE$VH_OBJECT_NAME VARCHAR(67) NOT NULL,
        IBE$VH_HEADER BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        IBE$VH_BODY BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        IBE$VH_DESCRIPTION BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
PRIMARY KEY (IBE$VH_ID));

/* Table: TB_ACORDOS, Owner: SYSDBA */
CREATE TABLE TB_ACORDOS (ACO_COD INTEGER NOT NULL,
        ACO_DCAD DATE,
        ACO_HORA TIME,
        LAB_COD INTEGER,
        CAS_CODIGO VARCHAR(6),
        ACO_VLRWEB NUMERIC(14, 4),
        ACO_VLRIMP NUMERIC(14, 4),
        ACO_VIGENTE INTEGER,
        ACO_DINA DATE,
        ACO_COVID VARCHAR(3),
CONSTRAINT PK_TB_ACORDOS PRIMARY KEY (ACO_COD));

/* Table: TB_ALELOS, Owner: SYSDBA */
CREATE TABLE TB_ALELOS (COD_ALE INTEGER NOT NULL,
        NM1_ALE VARCHAR(100),
        NM2_ALE VARCHAR(100),
        NM3_ALE VARCHAR(100),
        NM4_ALE VARCHAR(100),
        MAR_ALE VARCHAR(200),
        AL1_ALE VARCHAR(30),
        AL2_ALE VARCHAR(30),
        ORD_ALE INTEGER,
CONSTRAINT PK_TB_ALELOS PRIMARY KEY (COD_ALE));

/* Table: TB_ALELOS_FREQUENCIA, Owner: SYSDBA */
CREATE TABLE TB_ALELOS_FREQUENCIA (FRE_MARCADOR VARCHAR(10),
        FRE_ALELO DECIMAL(12, 1),
        FRE_FREQUENCIA DECIMAL(12, 6));

/* Table: TB_ALELOS_RESULTADOS, Owner: SYSDBA */
CREATE TABLE TB_ALELOS_RESULTADOS (ARE_MARCADOR VARCHAR(10),
        ARE_AL1_MAE DECIMAL(12, 2),
        ARE_AL2_MAE DECIMAL(12, 2),
        ARE_AL1_CRI DECIMAL(12, 2),
        ARE_AL2_CRI DECIMAL(12, 2),
        ARE_AL1_SPA DECIMAL(12, 2),
        ARE_AL2_SPA DECIMAL(12, 2),
        ARE_FREQUENCIA DECIMAL(12, 2),
        ARE_PI DECIMAL(12, 6),
        ARE_PROBA DECIMAL(12, 6),
        PRO_COD INTEGER);

/* Table: TB_ALELOS_TIPOS, Owner: SYSDBA */
CREATE TABLE TB_ALELOS_TIPOS (ATP_COD INTEGER,
        ATP_NOME VARCHAR(60),
        ATP_ORDEM INTEGER,
        ATP_TIPO VARCHAR(30),
        ATP_LMMIN DECIMAL(12, 2),
        ATP_LMMAX DECIMAL(12, 2));

/* Table: TB_ALELOS_TMP, Owner: SYSDBA */
CREATE TABLE TB_ALELOS_TMP (COD_TALE INTEGER NOT NULL,
        CASO_TALE VARCHAR(100),
        PESSOA_TALE VARCHAR(100),
        INICIAIS_TALE VARCHAR(100),
        TIPO_TALE VARCHAR(100),
        ALELO_TALE VARCHAR(200),
        VALOR1_TALE VARCHAR(30),
        VALOR2_TALE VARCHAR(30),
CONSTRAINT PK_TB_ALELOS_TMP_1 PRIMARY KEY (COD_TALE));

/* Table: TB_AUDITORIA, Owner: SYSDBA */
CREATE TABLE TB_AUDITORIA (PRO_COD INTEGER NOT NULL,
        HOS_USUA VARCHAR(60),
        AUD_DATA DATE,
        AUD_HORA VARCHAR(12),
        AUD_AVISO VARCHAR(200),
        AUD_EXECUCAO VARCHAR(100),
        AUD_CONTR INTEGER NOT NULL,
        AUD_CAM_ORIALT VARCHAR(300),
CONSTRAINT PK_TB_AUDITORIA PRIMARY KEY (AUD_CONTR));

/* Table: TB_BANCO, Owner: SYSDBA */
CREATE TABLE TB_BANCO (COD_BANCO VARCHAR(3) NOT NULL,
        DESC_BANCO VARCHAR(50),
CONSTRAINT PK_TB_BANCO PRIMARY KEY (COD_BANCO));

/* Table: TB_CASOS, Owner: SYSDBA */
CREATE TABLE TB_CASOS (CAS_CONTR INTEGER NOT NULL,
        CAS_CODIGO VARCHAR(6),
        CAS_DESC VARCHAR(60),
        CAS_VLR NUMERIC(14, 2),
        CAS_NOME0 VARCHAR(3),
        CAS_NOME1 VARCHAR(15),
        CAS_NOME2 VARCHAR(15),
        CAS_NOME3 VARCHAR(15),
        CAS_NOME4 VARCHAR(15),
        CAS_SIG1 VARCHAR(5),
        CAS_SIG2 VARCHAR(5),
        CAS_SIG3 VARCHAR(5),
        CAS_SIG4 VARCHAR(5),
CONSTRAINT PK_TB_CASOS PRIMARY KEY (CAS_CONTR));

/* Table: TB_CASO_ENDERECO, Owner: SYSDBA */
CREATE TABLE TB_CASO_ENDERECO (COR_COD INTEGER NOT NULL,
        COR_DESTINO VARCHAR(60),
        COR_END VARCHAR(80),
        COR_BAIRRO VARCHAR(40),
        COR_CID VARCHAR(40),
        COR_CEP VARCHAR(12),
        UF_SIGLA VARCHAR(2),
        PRO_COD INTEGER,
CONSTRAINT PK_TB_CASO_ENDERECO PRIMARY KEY (COR_COD));

/* Table: TB_CODIGO, Owner: SYSDBA */
CREATE TABLE TB_CODIGO (PRO_COD INTEGER NOT NULL,
        STATUS CHAR(1),
CONSTRAINT PK_TB_CODIGO PRIMARY KEY (PRO_COD));

/* Table: TB_COLABORADOR, Owner: SYSDBA */
CREATE TABLE TB_COLABORADOR (CLB_COD INTEGER NOT NULL,
        CLB_PIS VARCHAR(11),
        CLB_NOME VARCHAR(200),
CONSTRAINT PK_TB_COLABORADOR PRIMARY KEY (CLB_COD));

/* Table: TB_COLETADOR, Owner: SYSDBA */
CREATE TABLE TB_COLETADOR (COL_COD INTEGER NOT NULL,
        COL_ORDEM INTEGER NOT NULL,
        COL_NOME VARCHAR(200),
CONSTRAINT PK_TB_COLETADOR PRIMARY KEY (COL_COD));

/* Table: TB_COLETADOR_REL, Owner: SYSDBA */
CREATE TABLE TB_COLETADOR_REL (CODIGO INTEGER NOT NULL,
        ORDEM INTEGER NOT NULL,
        NOME VARCHAR(200),
CONSTRAINT PK_TB_COLETADOR_REL PRIMARY KEY (ORDEM));

/* Table: TB_COLETA_ADICIONAL, Owner: SYSDBA */
CREATE TABLE TB_COLETA_ADICIONAL (COA_ID INTEGER NOT NULL,
        PRO_COD INTEGER NOT NULL,
        COA_DATA DATE,
        COA_HORA VARCHAR(5),
        COA_OBS VARCHAR(50),
        LCO_COD INTEGER,
        COA_DATREC DATE,
CONSTRAINT PK_TB_COLETA_ADICIONAL PRIMARY KEY (COA_ID, PRO_COD));

/* Table: TB_COMARCA, Owner: SYSDBA */
CREATE TABLE TB_COMARCA (UF_SIGLA VARCHAR(2) NOT NULL,
        COM_COD INTEGER NOT NULL,
        COM_DESC VARCHAR(40),
        COM_SIGLA VARCHAR(2),
CONSTRAINT PK_TB_COMARCA PRIMARY KEY (UF_SIGLA, COM_COD));

/* Table: TB_COMPRA_KIT, Owner: SYSDBA */
CREATE TABLE TB_COMPRA_KIT (NUMERO_KIT INTEGER NOT NULL,
        NOME_SUPAI VARCHAR(60),
        CPF_SUPAI VARCHAR(14),
        ENDE_SUPAI VARCHAR(200),
        DATA_CADASTRO DATE,
CONSTRAINT PK_TB_COMPRA_KIT PRIMARY KEY (NUMERO_KIT));

/* Table: TB_CONTAALELO, Owner: SYSDBA */
CREATE TABLE TB_CONTAALELO (QTD_CODIGO INTEGER NOT NULL);

/* Table: TB_CONTROLE, Owner: SYSDBA */
CREATE TABLE TB_CONTROLE (CODIGO_PROCEDIMENTO INTEGER NOT NULL,
        CODIGO_PACIENTE INTEGER NOT NULL);

/* Table: TB_CORRESPONDENCIA, Owner: SYSDBA */
CREATE TABLE TB_CORRESPONDENCIA (END_COD INTEGER NOT NULL,
        PRO_COD INTEGER NOT NULL,
        OBS VARCHAR(20),
        TIPO VARCHAR(10),
        REGCORREIO VARCHAR(14),
        CORR_USU VARCHAR(20) NOT NULL,
        CORR_DATA DATE NOT NULL,
CONSTRAINT PK_TB_CORRESPONDENCIA PRIMARY KEY (END_COD, PRO_COD));

/* Table: TB_CREDITOS, Owner: SYSDBA */
CREATE TABLE TB_CREDITOS (ID_CREDITO INTEGER NOT NULL,
        JUI_COD INTEGER,
        PRO_COD INTEGER,
        CRED_QDCRE VARCHAR(10),
        CRE_DATA DATE,
        PRO_DTREC DATE,
        CRED_INICIAL INTEGER,
        CRED_FINAL INTEGER,
CONSTRAINT PK_TB_CREDITOS PRIMARY KEY (ID_CREDITO));

/* Table: TB_CREDITOS_TEMPORARIO, Owner: SYSDBA */
CREATE TABLE TB_CREDITOS_TEMPORARIO (ID_CREDITO INTEGER,
        JUI_COD INTEGER,
        PRO_COD INTEGER,
        CRED_QDCRE VARCHAR(10),
        CRE_DATA DATE,
        PRO_DTREC DATE);

/* Table: TB_DADOSPROCESSO, Owner: SYSDBA */
CREATE TABLE TB_DADOSPROCESSO (DPR_COD INTEGER NOT NULL,
        DPR_TIA VARCHAR(50),
        REQTE VARCHAR(100),
        REQDO VARCHAR(100),
        PRO_COD INTEGER NOT NULL);

/* Table: TB_ENDERECOS, Owner: SYSDBA */
CREATE TABLE TB_ENDERECOS (END_COD INTEGER NOT NULL,
        END_LOC VARCHAR(60),
        END_NMR VARCHAR(80),
        END_BAI VARCHAR(30),
        END_END VARCHAR(120),
        END_CID VARCHAR(40),
        END_CEP VARCHAR(40),
        UF_SIGLA VARCHAR(2),
        END_TRATA VARCHAR(30),
CONSTRAINT PK_TB_ENDERECOS PRIMARY KEY (END_COD));

/* Table: TB_EXAMES, Owner: SYSDBA */
CREATE TABLE TB_EXAMES (EXA_COD VARCHAR(10),
        EXA_DESC VARCHAR(100),
        EXA_UNM INTEGER,
        EXA_SIN VARCHAR(50),
        EXA_MET VARCHAR(200),
        EXA_VRE VARCHAR(30),
        EXA_VLAB NUMERIC(10, 2),
        EXA_VPAC NUMERIC(10, 2),
        EXA_RECM VARCHAR(500),
        EXA_MATE VARCHAR(200),
        EXA_OBSERV VARCHAR(2000));

/* Table: TB_EXTRACAO, Owner: SYSDBA */
CREATE TABLE TB_EXTRACAO (EXT_COD INTEGER NOT NULL,
        EXT_DATA DATE,
        MPEA_LOTE INTEGER NOT NULL,
        EXT_RESP VARCHAR(20),
        EXT_SUPER VARCHAR(20),
        SEQ_DTCORR DATE,
        SEQ_RESP VARCHAR(20),
        SEQ_SUPER VARCHAR(20),
        SEQ_FORLOTE VARCHAR(20),
        SEQ_ILSLOTE VARCHAR(20),
        SEQ_LADLOTE VARCHAR(20),
        SEQ_PIP10UL INTEGER DEFAULT 0,
        SEQ_PIP200UL INTEGER DEFAULT 0,
        SEQ_PIP1000UL INTEGER DEFAULT 0,
        REA_FTALOTE VARCHAR(20),
        REA_CHELEXLOTE VARCHAR(20),
        REA_AGUALOTE VARCHAR(20),
        AMPL_RESP VARCHAR(20),
        AMPL_SUPER VARCHAR(20),
        AMPL_DATA DATE,
        AMPL_KITLOTE VARCHAR(20),
        AMPL_TERM9700 INTEGER DEFAULT 0,
        AMPL_TERM2720 INTEGER DEFAULT 0,
        AMPL_PIP10UL INTEGER DEFAULT 0,
        AMPL_PIP200UL INTEGER DEFAULT 0,
        AMPL_PIP1000UL INTEGER DEFAULT 0,
        EQU_OUTROS VARCHAR(20),
        EQU_BLCTER19 INTEGER DEFAULT 0,
        EQU_BLCTER20 INTEGER DEFAULT 0,
        EQU_VORTEX18 INTEGER DEFAULT 0,
        EQU_AGIMAG25 INTEGER DEFAULT 0,
        EQU_BOMBVA30 INTEGER DEFAULT 0,
        EQU_CENTR31 INTEGER DEFAULT 0,
        EQU_PIP10UL INTEGER DEFAULT 0,
        EQU_PIP200UL INTEGER DEFAULT 0,
        EQU_PIP1000UL INTEGER DEFAULT 0,
        EQU_PIP10ULNUM INTEGER DEFAULT 0,
        EQU_PIP200ULNUM INTEGER DEFAULT 0,
        EQU_PIP1000ULNUM INTEGER DEFAULT 0,
CONSTRAINT PK_TB_EXTRACAO PRIMARY KEY (EXT_COD));

/* Table: TB_EXTRACAO_CASOS, Owner: SYSDBA */
CREATE TABLE TB_EXTRACAO_CASOS (EXTC_COD INTEGER NOT NULL,
        SUP_DATA DATE,
        SUP_SUPER VARCHAR(20),
        SUP_MEIOREM INTEGER DEFAULT 0,
        SUP_PESPARA VARCHAR(20),
        SUP_SIMGEAMO INTEGER DEFAULT 0,
        SUP_INCLMACRI INTEGER DEFAULT 0,
        SUP_INCLMASUP INTEGER DEFAULT 0,
        ANA_DTLEIT DATE,
        ANA_RESCONF VARCHAR(20),
        PRO_COD INTEGER NOT NULL,
        ANA_INICONFNCONF INTEGER DEFAULT 0,
        ANA_SIMGEAMO INTEGER DEFAULT 0,
        ANA_INCLMACRI INTEGER DEFAULT 0,
        ANA_INCLMASUP INTEGER DEFAULT 0,
        ANA_INCLUSAO INTEGER DEFAULT 0,
        ANA_MUTACAO INTEGER DEFAULT 0,
        ANA_MARCADOR VARCHAR(20),
        ANA_EXCLUSAO INTEGER DEFAULT 0,
        ANA_CONTRAPROVA INTEGER DEFAULT 0,
        ANA_CONFORME INTEGER DEFAULT 0,
        ANA_REPETICAO INTEGER DEFAULT 0,
        ANA_REPETICAOM INTEGER DEFAULT 0,
        ANA_REPETICAOC INTEGER DEFAULT 0,
        ANA_REPETICAOSP INTEGER DEFAULT 0,
        ANA_OUANADP18 INTEGER DEFAULT 0,
        ANA_OUANACROY INTEGER DEFAULT 0,
        ANA_OUANARESP VARCHAR(20),
        ANA_INCLUSIVO INTEGER DEFAULT 0,
        ANA_OUANADATA DATE,
        ANA_LADCOMPALE INTEGER DEFAULT 0,
        ANA_CONTRDNA INTEGER DEFAULT 0,
        MPEA_LOTE INTEGER NOT NULL,
CONSTRAINT PK_TB_EXTRACAO_CASOS PRIMARY KEY (EXTC_COD));

/* Table: TB_HISTORICO, Owner: SYSDBA */
CREATE TABLE TB_HISTORICO (HIS_CONTR INTEGER NOT NULL,
        PRO_COD INTEGER NOT NULL,
        ITE_COD INTEGER NOT NULL,
        HIS_DATA DATE,
        HIS_DOC VARCHAR(50),
        HIS_OBS VARCHAR(50),
CONSTRAINT PK_TB_HISTORICO PRIMARY KEY (HIS_CONTR, PRO_COD));

/* Table: TB_HOSTS, Owner: SYSDBA */
CREATE TABLE TB_HOSTS (HOS_NOME VARCHAR(50),
        HOS_USUA VARCHAR(20) NOT NULL,
        HOS_SENHA VARCHAR(10),
        RES_COD INTEGER,
        HOS_MAQUI VARCHAR(20),
        HOS_SITUACAO INTEGER DEFAULT 0 NOT NULL,
        HOS_DTULTALT DATE);

/* Table: TB_IMPRESSOES, Owner: SYSDBA */
CREATE TABLE TB_IMPRESSOES (PRO_COD INTEGER NOT NULL,
        ITE_COD INTEGER NOT NULL,
        IMP_TIPO VARCHAR(20),
        IMP_QDFL INTEGER,
        IMP_QDIM INTEGER,
        IMP_IMPR VARCHAR(50),
        IMP_DATA DATE,
        IMP_CONTR INTEGER NOT NULL,
CONSTRAINT PK_TB_IMPRESSOES PRIMARY KEY (IMP_CONTR));

/* Table: TB_ITEM, Owner: SYSDBA */
CREATE TABLE TB_ITEM (ITE_COD INTEGER NOT NULL,
        ITE_DESC VARCHAR(60),
        ITE_ORG CHAR(1),
CONSTRAINT PK_TB_ITEM PRIMARY KEY (ITE_COD));

/* Table: TB_JUIZ, Owner: SYSDBA */
CREATE TABLE TB_JUIZ (JUI_COD INTEGER NOT NULL,
        JUI_DESC VARCHAR(50),
        JUI_SEXO CHAR(1),
        JUI_CREDITO CHAR(1),
CONSTRAINT PK_TB_JUIZ PRIMARY KEY (JUI_COD));

/* Table: TB_KITS, Owner: SYSDBA */
CREATE TABLE TB_KITS (KIT_COD INTEGER NOT NULL,
        KIT_TIP INTEGER,
        KIT_NUM INTEGER NOT NULL,
        COL_COD INTEGER NOT NULL,
        KIT_DENV DATE,
        KIT_DRET DATE,
        KIT_CEXA INTEGER,
        KIT_STATUS CHAR(1),
        KIT_RASTREAR VARCHAR(20),
CONSTRAINT PK_TB_KITS PRIMARY KEY (KIT_COD));

/* Table: TB_LABORATORIOS, Owner: SYSDBA */
CREATE TABLE TB_LABORATORIOS (LAB_COD INTEGER NOT NULL,
        LAB_NOME VARCHAR(60),
        LAB_SEXO VARCHAR(10),
        LAB_CRM VARCHAR(15),
        LAB_LABT VARCHAR(60),
        LAB_FONE VARCHAR(25),
        LAB_END VARCHAR(80),
        LAB_CID VARCHAR(40),
        UF_SIGLA VARCHAR(2),
        LAB_INTEXT VARCHAR(8),
        LAB_FGVLR VARCHAR(3),
        LAB_FGBOLETO VARCHAR(3),
        COM_COD INTEGER,
        LAB_FG_EXPORTA INTEGER,
        LAB_COD_INTERNET SMALLINT,
        LAB_RESUL_INTERNET SMALLINT,
PRIMARY KEY (LAB_COD));

/* Table: TB_LCOLETA, Owner: SYSDBA */
CREATE TABLE TB_LCOLETA (LCO_COD INTEGER NOT NULL,
        LCO_NOME VARCHAR(60),
        LCO_SEXO INTEGER,
        LCO_CRM VARCHAR(15),
        LCO_LABT VARCHAR(60),
        LCO_FONE VARCHAR(25),
        LCO_END VARCHAR(80),
        LCO_CID VARCHAR(40),
        UF_SIGLA VARCHAR(2),
        LCO_TLIE INTEGER,
        LCO_CATE INTEGER,
        LCO_TRAT INTEGER,
        LCO_CEL VARCHAR(15),
        LCO_RES VARCHAR(15),
        LCO_EMAIL VARCHAR(50),
        LCO_SITE VARCHAR(50),
        LCO_CEP VARCHAR(12),
        LCO_DTRE DATE,
        LCO_DCAD DATE,
        LCO_NUMCARTCORREIO INTEGER,
        LCO_SITUACAO CHAR(1),
        LCO_DNASC DATE,
        LCO_CPFCNPJ VARCHAR(20),
        LCO_BANCO VARCHAR(20),
        LCO_AGENCIA VARCHAR(20),
        LCO_CONTA VARCHAR(30),
        LCO_MINKIT INTEGER,
        LCO_PIX VARCHAR(100),
CONSTRAINT PK_TB_LCOLETA PRIMARY KEY (LCO_COD));

/* Table: TB_MAPA_EXTAMPLI, Owner: SYSDBA */
CREATE TABLE TB_MAPA_EXTAMPLI (PRO_COD INTEGER,
        MPEA_DATA DATE NOT NULL,
        MPEA_LOTE INTEGER NOT NULL,
        MPEA_ORD INTEGER,
        PES_INICIAIS VARCHAR(10),
        SIT_SIGLA VARCHAR(5));

/* Table: TB_MAPA_EXTAMPLI_CASOS, Owner: SYSDBA */
CREATE TABLE TB_MAPA_EXTAMPLI_CASOS (MPEA_LOTE INTEGER NOT NULL,
        PRO_COD INTEGER NOT NULL,
        MPEA_ORD INTEGER NOT NULL,
        PES_INICIAIS VARCHAR(10),
        SIT_SIGLA VARCHAR(5),
CONSTRAINT PK_TB_MAPA_EXTAMPLI_CASOS PRIMARY KEY (PRO_COD, MPEA_LOTE, MPEA_ORD));

/* Table: TB_MEDICOS, Owner: SYSDBA */
CREATE TABLE TB_MEDICOS (MED_CRM VARCHAR(15),
        MED_NOME VARCHAR(60),
        MED_CID VARCHAR(40),
        MED_COD INTEGER NOT NULL,
CONSTRAINT PK_TB_MEDICOS PRIMARY KEY (MED_COD));

/* Table: TB_PACIENTES, Owner: SYSDBA */
CREATE TABLE TB_PACIENTES (PES_COD INTEGER NOT NULL,
        PES_NOME VARCHAR(60),
        PES_ESCV VARCHAR(12),
        PES_IDA INTEGER,
        PES_SEXO VARCHAR(10),
        PES_DNAS DATE,
        PES_END VARCHAR(150),
        PES_CIES VARCHAR(50),
        PES_FRES VARCHAR(16),
        PES_FCEL VARCHAR(16),
        PES_CPF VARCHAR(15),
        PES_RG VARCHAR(30),
        PES_COD_INTERNET SMALLINT,
        PES_EMAIL VARCHAR(100),
        PES_NUMCAR VARCHAR(30),
        PES_CLAORI VARCHAR(20),
        PES_RACA VARCHAR(30),
        PES_NUNEND VARCHAR(10),
        PES_CEP VARCHAR(10),
        PES_BAIRRO VARCHAR(50),
        PES_SINTOMAS VARCHAR(200),
        PES_UF VARCHAR(2),
        PES_SINTOMA1 SMALLINT,
        PES_SINTOMA2 SMALLINT,
        PES_SINTOMA3 SMALLINT,
        PES_SINTOMA4 SMALLINT,
        PES_SINTOMA5 SMALLINT,
        PES_SINTOMA6 SMALLINT,
        PES_SINTOMA7 SMALLINT,
        PES_SINTOMA8 SMALLINT,
        PES_SINTOMA9 SMALLINT,
        PES_SINTOMA10 SMALLINT,
        PES_PASS VARCHAR(30),
CONSTRAINT PK_TB_PACIENTES PRIMARY KEY (PES_COD));

/* Table: TB_PARAMETRO, Owner: SYSDBA */
CREATE TABLE TB_PARAMETRO (PAM_COD INTEGER NOT NULL,
        PAM_DPADR VARCHAR(200) NOT NULL,
        PAM_DDEST VARCHAR(200) NOT NULL,
        PAM_UNID VARCHAR(3) NOT NULL,
        PAM_DRCOL VARCHAR(600),
        PAM_DPADRDG VARCHAR(200),
        PAM_DREXCEL VARCHAR(300),
        PAM_DIRMPEXTRACAO VARCHAR(300),
        PAM_DIRMPEXTRACAOXLS VARCHAR(300),
        PAM_VLRJUD DECIMAL(10, 2),
        PAM_VLREXTRA DECIMAL(10, 2),
        PAM_VLRMP DECIMAL(10, 2),
        PAM_VLRDP DECIMAL(10, 2),
        PAM_VLRCT DECIMAL(10, 2),
        PAM_DRPDF VARCHAR(300),
        PAM_IMPETQ INTEGER DEFAULT 0,
        PAM_DIRDOC VARCHAR(300),
        PAM_DIRINTEGRADOC VARCHAR(300),
        PAM_DIRINTEGRAOF VARCHAR(300),
        PAM_ULTCRED INTEGER,
CONSTRAINT PK_TB_PARAMETRO PRIMARY KEY (PAM_COD));

/* Table: TB_PARCELAS, Owner: SYSDBA */
CREATE TABLE TB_PARCELAS (PRO_COD INTEGER NOT NULL,
        PAR_NPARC INTEGER,
        PAR_VLR NUMERIC(14, 2),
        PAR_DATA DATE,
        PAR_SIT INTEGER,
        PAR_TPPG VARCHAR(30),
        CONTROLE INTEGER NOT NULL,
        PAR_OBS VARCHAR(80),
        PAR_HORA TIME DEFAULT CURRENT_TIME ,
        PAR_ONDE VARCHAR(20),
        PAR_DATAPREVISTA DATE,
        PAR_NMFOR VARCHAR(100),
CONSTRAINT PK_TB_PARCELAS PRIMARY KEY (PRO_COD, CONTROLE));

/* Table: TB_PEDIDOS_WEB, Owner: SYSDBA */
CREATE TABLE TB_PEDIDOS_WEB (PWB_COD INTEGER NOT NULL,
        PWB_DCAD DATE,
        PWB_PROT VARCHAR(30),
        PWB_IDPD VARCHAR(50),
        PWB_NOME VARCHAR(100),
        PWB_DNAS DATE,
        PWB_EMAIL VARCHAR(70),
        PWB_PASS VARCHAR(30),
        PWB_CPF VARCHAR(30),
        PWB_CVN INTEGER,
        PWB_TELE VARCHAR(30),
        PWB_SEXO VARCHAR(30),
        PWB_DCOLE DATE,
        PWB_HCOLE TIME,
        PWB_FG_RESUL SMALLINT,
        PWB_RG VARCHAR(30),
        PWB_ORD SMALLINT,
        PWB_CLAORI VARCHAR(30),
        PWB_CONVENIO VARCHAR(40),
        PWB_PRAZO VARCHAR(130),
        PWB_NUNCAR VARCHAR(20),
        PWB_RESULTADO VARCHAR(30),
        PWB_RACA VARCHAR(30),
        PWB_NUNEND VARCHAR(10),
        PWB_CEP VARCHAR(10),
        PWB_BAIRRO VARCHAR(50),
        PWB_SINTOMAS VARCHAR(200),
        PWB_UF VARCHAR(2),
        PWB_END VARCHAR(150),
        PWB_CIES VARCHAR(50),
        PWB_ESCV VARCHAR(20),
        PWB_SINTOMA1 SMALLINT,
        PWB_SINTOMA2 SMALLINT,
        PWB_SINTOMA3 SMALLINT,
        PWB_SINTOMA4 SMALLINT,
        PWB_SINTOMA5 SMALLINT,
        PWB_SINTOMA6 SMALLINT,
        PWB_SINTOMA7 SMALLINT,
        PWB_SINTOMA8 SMALLINT,
        PWB_SINTOMA9 SMALLINT,
        PWB_SINTOMA10 SMALLINT,
        PWB_AUTOMA INTEGER DEFAULT 0,
        PWB_EXAME SMALLINT,
CONSTRAINT PK_TB_PEDIDOS_WEB PRIMARY KEY (PWB_COD));

/* Table: TB_PESQUISA, Owner: SYSDBA */
CREATE TABLE TB_PESQUISA (PEQ_COD INTEGER NOT NULL,
        PEQ_NOME VARCHAR(80),
        PEQ_NDOC VARCHAR(80),
        PEQ_ESTC VARCHAR(80),
        PEQ_DTNAS DATE,
        PEQ_LCNAS VARCHAR(100),
        PEQ_LCRE VARCHAR(100),
        PEQ_FONE VARCHAR(20),
CONSTRAINT PK_TB_PESQUISA PRIMARY KEY (PEQ_COD));

/* Table: TB_PESSOAS, Owner: SYSDBA */
CREATE TABLE TB_PESSOAS (PRO_COD INTEGER NOT NULL,
        PES_COD INTEGER NOT NULL,
        PES_NOME VARCHAR(60),
        PES_INICIAIS VARCHAR(10),
        PES_SIT INTEGER,
        PES_DTNAS DATE,
        PES_LCNAS VARCHAR(50),
        PES_SEXO CHAR(1),
        PES_TDOC VARCHAR(30),
        PES_NDOC VARCHAR(200),
CONSTRAINT PK_TB_PESSOAS PRIMARY KEY (PRO_COD, PES_COD));

/* Table: TB_PROCEDIMENTOS, Owner: SYSDBA */
CREATE TABLE TB_PROCEDIMENTOS (PRO_COD INTEGER NOT NULL,
        PRO_DCAD DATE,
        PES_COD INTEGER,
        LAB_COD INTEGER,
        MED_CRM VARCHAR(15),
        EXA_COD VARCHAR(10),
        PRO_DCOL DATE,
        PRO_DENT DATE,
        PRO_GENO VARCHAR(50),
        PRO_VLOG NUMERIC(14, 4),
        PRO_RESUL VARCHAR(30),
        PRO_OBS VARCHAR(100),
        PRO_UINT NUMERIC(14, 4),
        PRO_CMLI NUMERIC(14, 4),
        PRO_PROT VARCHAR(12),
        PRO_APA VARCHAR(3),
        PRO_DREC DATE,
        PRO_ATEND VARCHAR(40),
        PRO_TIPR VARCHAR(10),
        PRO_HCAD VARCHAR(5),
        PRO_VALOR NUMERIC(10, 2),
        PRO_HCOL TIME,
        PRO_FG_RESUL SMALLINT,
        PRO_PRAZO VARCHAR(30),
        PRO_IDWEB INTEGER,
        PRO_TIPPAG VARCHAR(30),
        PRO_HASH VARCHAR(255),
        PRO_FG_SITE INTEGER,
CONSTRAINT PK_TB_PROCEDIMENTOS PRIMARY KEY (PRO_COD));

/* Table: TB_PROCEDIMENTOS_CARGA, Owner: SYSDBA */
CREATE TABLE TB_PROCEDIMENTOS_CARGA (PROC_COD INTEGER NOT NULL,
        PRO_COD INTEGER,
        PROC_DATA DATE DEFAULT CURRENT_DATE,
        PROC_HORA TIME DEFAULT CURRENT_TIME,
        HOS_USUA VARCHAR(20),
CONSTRAINT PK_TB_PROCEDIMENTOS_CARGA PRIMARY KEY (PROC_COD));

/* Table: TB_PROCEDIMENTOS_RESULTADO, Owner: SYSDBA */
CREATE TABLE TB_PROCEDIMENTOS_RESULTADO (PROR_COD INTEGER NOT NULL,
        PRO_COD INTEGER,
        PROR_DAT DATE,
        PRO_VLOG NUMERIC(14, 9),
        PRO_UINT NUMERIC(14, 4),
        PRO_CMLI NUMERIC(14, 4),
        PRO_RESUL VARCHAR(100),
        PRO_RESUL3 VARCHAR(100),
        PRO_RESUL2 VARCHAR(100),
        PRO_RESUL4 VARCHAR(100),
CONSTRAINT PK_TB_PROCEDIMENTOS_RESULTADO PRIMARY KEY (PROR_COD));

/* Table: TB_PROCESSO, Owner: SYSDBA */
CREATE TABLE TB_PROCESSO (PRO_COD INTEGER NOT NULL,
        PRO_ANO INTEGER,
        PRO_NPERC VARCHAR(17),
        PRO_TIPO INTEGER,
        PRO_AUTO VARCHAR(30),
        UF_SIGLA VARCHAR(2),
        CAS_CODIGO VARCHAR(6),
        COM_COD INTEGER,
        VAR_COD INTEGER,
        LCO_COD INTEGER,
        PRO_HCOLE VARCHAR(5),
        PRO_DCOLE DATE,
        PRO_HREC VARCHAR(5),
        PRO_DREC DATE,
        PRO_DRESU DATE,
        PRO_SIT INTEGER,
        PRO_NCOMP INTEGER,
        PRO_RESUL INTEGER,
        PRO_PROB VARCHAR(15),
        PRO_ARETI VARCHAR(100),
        JUI_COD INTEGER,
        FG_PROP VARCHAR(1),
        PRO_USUCAD VARCHAR(20),
        PRO_NUMLAUDO VARCHAR(20),
        PRO_RASTREAR VARCHAR(20),
        PRO_CARREGACREDITO CHAR(1),
        PRO_CREDITODNA VARCHAR(20),
        PRO_HTREC VARCHAR(5),
        PRO_LACRE VARCHAR(20),
        PRO_FG_EXTERNO INTEGER DEFAULT 0,
        PRO_FG_RESUL INTEGER DEFAULT 0,
        PRO_DATA_EXTERNO DATE,
        FG_CALCCRED INTEGER DEFAULT 0,
CONSTRAINT PK_TB_PROCESSO PRIMARY KEY (PRO_COD));

/* Table: TB_PROCESSO_CREDITO, Owner: SYSDBA */
CREATE TABLE TB_PROCESSO_CREDITO (PRO_COD INTEGER NOT NULL,
        UF_SIGLA VARCHAR(2),
        COM_COD INTEGER,
        VAR_COD INTEGER,
        NUM_CREDITO INTEGER,
        DAT_CREDITO DATE,
CONSTRAINT PK_TB_PROCESSO_CREDITO PRIMARY KEY (PRO_COD));

/* Table: TB_REGISTROS_PONTO, Owner: SYSDBA */
CREATE TABLE TB_REGISTROS_PONTO (RGP_SEQ INTEGER NOT NULL,
        RGP_PIS VARCHAR(11),
        RGP_DTREG DATE,
        RGP_HRREG TIME,
        RGP_DTIMP DATE,
CONSTRAINT PK_TB_REGISTROS_PONTO PRIMARY KEY (RGP_SEQ));

/* Table: TB_REGRA, Owner: SYSDBA */
CREATE TABLE TB_REGRA (REG_COD INTEGER NOT NULL,
        REG_MOD VARCHAR(20) NOT NULL,
        ITE_COD INTEGER NOT NULL,
        REG_TIPO INTEGER NOT NULL,
        REG_PASTA VARCHAR(20) NOT NULL,
        REG_CPNOM VARCHAR(5) NOT NULL,
CONSTRAINT PK_TB_REGRA PRIMARY KEY (REG_COD));

/* Table: TB_RESTRICAO, Owner: SYSDBA */
CREATE TABLE TB_RESTRICAO (RES_COD INTEGER NOT NULL,
        RES_DESC VARCHAR(200),
CONSTRAINT PK_TB_RESTRICAO PRIMARY KEY (RES_COD));

/* Table: TB_SEQUENCIAL, Owner: SYSDBA */
CREATE TABLE TB_SEQUENCIAL (SEQUENCIAL INTEGER);

/* Table: TB_SITUACAO, Owner: SYSDBA */
CREATE TABLE TB_SITUACAO (SIT_COD INTEGER NOT NULL,
        SIT_NM VARCHAR(20),
        SIT_SIGLA VARCHAR(5),
        SIT_ORDEM INTEGER,
CONSTRAINT PK_TB_SITUACAO PRIMARY KEY (SIT_COD));

/* Table: TB_STATUS_PROCEDIMENTO, Owner: SYSDBA */
CREATE TABLE TB_STATUS_PROCEDIMENTO (PRO_COD INTEGER,
        STP_DATA DATE,
        STP_DESC VARCHAR(60),
        STP_STATUS INTEGER);

/* Table: TB_TEMP_CREDITO, Owner: SYSDBA */
CREATE TABLE TB_TEMP_CREDITO (ID_CREDITO INTEGER NOT NULL,
        TCRED_NUM INTEGER NOT NULL,
        TCRED_JUIZ VARCHAR(100));

/* Table: TB_TEMP_MEC, Owner: SYSDBA */
CREATE TABLE TB_TEMP_MEC (MPEA_LOTE INTEGER NOT NULL,
        PRO_COD INTEGER NOT NULL,
        MPEA_ORD INTEGER NOT NULL,
        PES_INICIAIS VARCHAR(10),
        SIT_SIGLA VARCHAR(5));

/* Table: TB_UF, Owner: SYSDBA */
CREATE TABLE TB_UF (UF_SIGLA VARCHAR(2) NOT NULL,
        UF_DESC VARCHAR(20),
CONSTRAINT PK_TB_UF PRIMARY KEY (UF_SIGLA));

/* Table: TB_VARAS, Owner: SYSDBA */
CREATE TABLE TB_VARAS (UF_SIGLA VARCHAR(2) NOT NULL,
        COM_COD INTEGER NOT NULL,
        VAR_COD INTEGER NOT NULL,
        VAR_DESC VARCHAR(40),
        JUI_COD INTEGER,
        VAR_SIGLA VARCHAR(3),
        VAR_END VARCHAR(80),
        VAR_BAIRRO VARCHAR(40),
        VAR_CID VARCHAR(40),
        VAR_CEP VARCHAR(12),
CONSTRAINT PK_TB_VARAS PRIMARY KEY (UF_SIGLA, COM_COD, VAR_COD));

/*  Index definitions for all user tables */
CREATE INDEX IBE$LOG_BLOB_FIELDS_IDX1 ON IBE$LOG_BLOB_FIELDS (LOG_TABLES_ID);
CREATE INDEX IBE$LOG_FIELDS_IDX1 ON IBE$LOG_FIELDS (LOG_TABLES_ID);
CREATE INDEX IBE$LOG_KEYS_IDX1 ON IBE$LOG_KEYS (LOG_TABLES_ID);
CREATE INDEX IDX_COD ON TB_ALELOS (NM1_ALE);
CREATE INDEX IDX_NOME ON TB_ALELOS (NM2_ALE);
CREATE INDEX TB_ALELOS_IDX_VL ON TB_ALELOS (AL1_ALE, AL2_ALE);
CREATE INDEX TB_AUDITORIA_DT ON TB_AUDITORIA (AUD_DATA);
CREATE INDEX TB_AUDITORIA_DTCOD ON TB_AUDITORIA (PRO_COD, AUD_DATA);
CREATE INDEX TB_AUDITORIA_PRO_COD ON TB_AUDITORIA (PRO_COD);
CREATE INDEX TB_PESSOAS_IDX1 ON TB_PESSOAS (PES_NOME, PES_SIT);
CREATE INDEX TB_PROCESSO_IDX1 ON TB_PROCESSO (UF_SIGLA, CAS_CODIGO, COM_COD, VAR_COD, LCO_COD, PRO_DRESU, PRO_DREC);
CREATE INDEX TB_PROCESSO_PERICIA ON TB_PROCESSO (PRO_NPERC);

ALTER TABLE TB_CASO_ENDERECO ADD CONSTRAINT FK_TB_CASO_ENDERECO_1 FOREIGN KEY (UF_SIGLA) REFERENCES TB_UF (UF_SIGLA);

ALTER TABLE TB_KITS ADD CONSTRAINT FK_TB_KITS_1 FOREIGN KEY (COL_COD) REFERENCES TB_COLETADOR (COL_COD) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TB_LCOLETA ADD CONSTRAINT FK_TB_LCOLETA_1 FOREIGN KEY (UF_SIGLA) REFERENCES TB_UF (UF_SIGLA) ON UPDATE CASCADE;

/* View: VI_ALELOSENCONTRADOS, Owner: SYSDBA */
CREATE VIEW VI_ALELOSENCONTRADOS (CONTADOR, CODIGO) AS

select count(ca.qtd_codigo), ca.qtd_codigo from tb_contaalelo ca
group by qtd_codigo
;

/* View: VI_BUSCA_PACIENTE, Owner: SYSDBA */
CREATE VIEW VI_BUSCA_PACIENTE (PES_COD, PES_CPF) AS

select p.pes_cod, cast(REPLACE(REPLACE(TRIM(p.PES_CPF),'-',''),'.','') as bigint) PES_CPF
from TB_PACIENTES p;

/* View: VI_STATUS_CASOS, Owner: SYSDBA */
CREATE VIEW VI_STATUS_CASOS (CASO, CADASTRADO, COLETADO, LABORATORIO, RESULTADO) AS

select P.pro_cod,
(select * from sp_formata_data(p.pro_drec)),
(select * from sp_formata_data(p.pro_dcole)),
(select * from sp_formata_data(H.his_data)),
(select * from sp_formata_data(p.pro_dresu))
from tb_processo p left outer join TB_HISTORICO h on h.pro_cod=p.pro_cod AND H.ite_cod = 61;

/* View: VI_DADOS_SENSE, Owner: SYSDBA */
CREATE VIEW VI_DADOS_SENSE (CODIGO, ANO, TIPO, UF, VARA, COMARCA, CASO, ITEM, LOCAL_COLETA, VALOR, TIPO_PAGAMENTO) AS

select
p.pro_cod Codigo, 
p.pro_ano Ano,
case p.pro_tipo
 when 1 then 'Judicial'
 when 2 then 'ExtraJudicial'
 when 3 then 'Ministério Público' 
 when 4 then 'Defensoria Pública' 
 when 5 then 'Delegacia de Polícia' 
 when 6 then 'Justiça Comunitária' 
 when 7 then 'Conselho Tutelar' 
 when 8 then 'Promotoria de Justiça' 
 when 9 then 'Paternidade Responsável' 
 when 10 then 'Núcleo de Prática Forense' 
end Tipo ,
p.uf_sigla UF,
v.var_desc VARA,
cm.com_desc COMARCA,
pr.cas_desc CASO,
i.ite_desc ITEM,
c.lco_nome LOCAL_COLETA,
PARC.par_vlr VALOR,
PARC.par_tppg TIPO_PAGAMENTO
from tb_PROCESSO p 
JOIN tb_LCOLETA c ON (p.lco_cod = c.lco_cod)
left outer JOIN tb_VARAS v  ON (v.uf_sigla = p.uf_sigla) and (v.com_cod = p.com_cod) and (v.var_cod = p.var_cod) 
JOIN tb_COMARCA cm ON (cm.uf_sigla = p.uf_sigla) and (cm.com_cod = p.com_cod)
JOIN tb_CASOS pr ON (p.cas_codigo = pr.cas_codigo) 
JOIN tb_HISTORICO h ON (p.pro_cod = h.pro_cod) 
JOIN tb_ITEM i ON (h.ite_cod = i.ite_cod)
LEFT OUTER JOIN tb_parcelas PARC ON PARC.pro_cod = P.pro_cod;

/* View: VI_QUANTIDADE_KITS, Owner: SYSDBA */
CREATE VIEW VI_QUANTIDADE_KITS (CODIGO, NOME, CIDADE, MINIMO_KIT, ATUAL_KIT, ULTIMA_DATA_ENVIO) AS



select l.lco_cod, l.lco_nome, l.lco_cid,
   l.lco_minkit,
(select count(k.kit_num) from tb_kits k  where l.lco_cod=k.col_cod and k.kit_status = 'A') atualkit,
(select max(k.kit_denv) from tb_kits k  where l.lco_cod=k.col_cod and k.kit_status = 'A') ultenvio
from tb_lcoleta l
where l.lco_situacao  = 'A'
;

/* View: VI_ACORDOS, Owner: SYSDBA */
CREATE VIEW VI_ACORDOS (CAS_CODIGO, CAS_DESC, CAS_VLRIM, CAS_VLRWB, LAB_COD, LAB_LABT, VIGENTE) AS

select c.cas_codigo, c.cas_desc, a.aco_vlrimp, a.aco_vlrweb, a.lab_cod, l.lab_labt ,
case when (a.aco_vigente = 1) then 'Sim' else 'Não' end VIGENTE
from tb_acordos a join tb_casos c on c.cas_codigo=a.cas_codigo
                           join tb_laboratorios l on l.lab_cod=a.lab_cod;

/* View: VI_ALELO_LIMITES, Owner: SYSDBA */
CREATE VIEW VI_ALELO_LIMITES (VAL_MARCADOR, VAL_MARCADOR_MIN, VAL_MARCADOR_MAX) AS

select F.fre_marcador VAL_MARCADOR, MIN(F.fre_alelo) VAL_MARCADOR_MIN, MAX(F.fre_alelo) VAL_MARCADOR_MAX
from tb_alelos_frequencia F
GROUP BY F.fre_marcador;

/* View: VI_VALOR_COLETADOR, Owner: SYSDBA */
CREATE VIEW VI_VALOR_COLETADOR (CASO, VALORCASO, VALOR) AS

select p.pro_cod,
cast(sum(pa.par_vlr) AS NUMERIC(15,2)) valor_caso,
case when ((sum(pa.par_vlr) >= 11) and (sum(pa.par_vlr) <= 350)) then 30 else
case when ((sum(pa.par_vlr) >= 0) and (sum(pa.par_vlr) <= 10)) then 60 else
case when ((sum(pa.par_vlr) >= 351) and (sum(pa.par_vlr) <= 499)) then 50 else
case when ((sum(pa.par_vlr) >= 500 and sum(pa.par_vlr) <= 999)) then 60 else 120 end end end end
from tb_PROCESSO p JOIN tb_parcelas pa on pa.pro_cod=p.pro_cod
group by p.pro_cod;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */
CREATE PROCEDURE BU_ALELOS (VALORMARCADOR1 VARCHAR(10) CHARACTER SET NONE,
VALORMARCADOR2 VARCHAR(10) CHARACTER SET NONE,
MARCADOR VARCHAR(30) CHARACTER SET NONE)
RETURNS (MENSAGEM VARCHAR(30) CHARACTER SET NONE)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE SP_DIA_SEMANA (P_DATA DATE)
RETURNS (S_DIA VARCHAR(15) CHARACTER SET WIN1252)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE SP_FORMATA_DATA (DATA DATE)
RETURNS (RESULTADO VARCHAR(10) CHARACTER SET NONE)
AS 
BEGIN SUSPEND; END ^

ALTER PROCEDURE BU_ALELOS (VALORMARCADOR1 VARCHAR(10) CHARACTER SET NONE,
VALORMARCADOR2 VARCHAR(10) CHARACTER SET NONE,
MARCADOR VARCHAR(30) CHARACTER SET NONE)
RETURNS (MENSAGEM VARCHAR(30) CHARACTER SET NONE)
AS 

begin
  insert into tb_contaalelo (qtd_codigo) select distinct nm1_ale from tb_alelos where al1_ale = :valormarcador1 and al2_ale = :ValorMarcador2 and mar_ale = :Marcador;
  suspend;
end ^

ALTER PROCEDURE SP_DIA_SEMANA (P_DATA DATE)
RETURNS (S_DIA VARCHAR(15) CHARACTER SET WIN1252)
AS 
declare variable V_DIA integer;
BEGIN
  V_DIA = EXTRACT(WEEKDAY FROM :P_DATA);
  S_DIA =
   CASE :V_DIA
     WHEN 0 THEN 'DOMINGO'
     WHEN 1 THEN 'SEGUNDA-FEIRA'
     WHEN 2 THEN 'TERÇA-FEIRA'
     WHEN 3 THEN 'QUARTA-FEIRA'
     WHEN 4 THEN 'QUINTA-FEIRA'
     WHEN 5 THEN 'SEXTA-FEIRA'
     WHEN 6 THEN 'SÁBADO'
   END;
  SUSPEND;
END ^

ALTER PROCEDURE SP_FORMATA_DATA (DATA DATE)
RETURNS (RESULTADO VARCHAR(10) CHARACTER SET NONE)
AS 
BEGIN
      -- Sem data?
      IF(DATA IS NULL)THEN
        -- Sem resultado tambem.
        RESULTADO = NULL;
      ELSE
        -- Converte a data p/ texto no formato brasileiro.
        RESULTADO = (LPAD(EXTRACT(DAY FROM DATA), 2, '0') || '/' ||
                     LPAD(EXTRACT(MONTH FROM DATA), 2, '0') || '/' ||
                     LPAD(EXTRACT(YEAR FROM DATA), 4, '0'));
      -- Retorna o resultado.
      SUSPEND;
    END ^
SET TERM ; ^
COMMIT WORK ;
SET AUTODDL ON;
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER IBE$LOG_TABLES_BD FOR IBE$LOG_TABLES 
ACTIVE BEFORE DELETE POSITION 0 
AS
BEGIN
  DELETE FROM IBE$LOG_FIELDS WHERE LOG_TABLES_ID = OLD.ID;
  DELETE FROM IBE$LOG_BLOB_FIELDS WHERE LOG_TABLES_ID = OLD.ID;
  DELETE FROM IBE$LOG_KEYS WHERE LOG_TABLES_ID = OLD.ID;
END ^

CREATE TRIGGER IBE$VERSION_HISTORY_BI FOR IBE$VERSION_HISTORY 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.IBE$VH_ID IS NULL) THEN
    NEW.IBE$VH_ID = GEN_ID(IBE$VERSION_HISTORY_ID_GEN,1);
  NEW.IBE$VH_USER_NAME = USER;
  NEW.IBE$VH_MODIFY_DATE = 'NOW';
END ^

CREATE TRIGGER TG_GERA_CODIGO_ALELOS FOR TB_ALELOS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.COD_ALE IS NULL) THEN NEW.COD_ALE = GEN_ID(gen_tb_alelos_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_ALELOS_TMP FOR TB_ALELOS_TMP 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.COD_TALE IS NULL) THEN NEW.COD_TALE = GEN_ID(gen_tb_alelos_tmp_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_AUDITORIA FOR TB_AUDITORIA 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.AUD_CONTR IS NULL) THEN NEW.AUD_CONTR = GEN_ID(gen_tb_auditoria_id,1);

END ^

CREATE TRIGGER CHECK_2 FOR TB_COLETADOR 
ACTIVE AFTER UPDATE POSITION 1 
 ^

CREATE TRIGGER CHECK_3 FOR TB_COLETADOR 
ACTIVE AFTER DELETE POSITION 1 
 ^

CREATE TRIGGER TG_GERA_CODIGO_COA FOR TB_COLETA_ADICIONAL 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.COA_ID IS NULL) THEN NEW.COA_ID = GEN_ID(GEN_TB_COLETA_ADICIONAL_ID,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_CREDITOS FOR TB_CREDITOS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.ID_CREDITO IS NULL) THEN NEW.ID_CREDITO = GEN_ID(gen_tb_creditos_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_ENDERECOS FOR TB_ENDERECOS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.END_COD IS NULL) THEN NEW.END_COD = GEN_ID(gen_tb_enderecos_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_EXTRACAO FOR TB_EXTRACAO 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.EXT_COD IS NULL) THEN NEW.EXT_COD = GEN_ID(gen_tb_extracao_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_EXTRACAO_CASOS FOR TB_EXTRACAO_CASOS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.EXTC_COD IS NULL) THEN NEW.EXTC_COD = GEN_ID(gen_tb_extracao_casos_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_HISTORICO FOR TB_HISTORICO 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.HIS_CONTR IS NULL) THEN NEW.HIS_CONTR = GEN_ID(gen_tb_historico_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_IMPRESSOES FOR TB_IMPRESSOES 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.IMP_CONTR IS NULL) THEN NEW.IMP_CONTR = GEN_ID(gen_tb_impressoes_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_KITS FOR TB_KITS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.KIT_COD IS NULL) THEN NEW.KIT_COD = GEN_ID(gen_tb_kits_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_PARCELAS FOR TB_PARCELAS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.CONTROLE IS NULL) THEN NEW.CONTROLE = GEN_ID(gen_tb_parcelas_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_PESQUISA FOR TB_PESQUISA 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.PEQ_COD IS NULL) THEN NEW.PEQ_COD = GEN_ID(gen_tb_pesquisa_id,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_PESSOA FOR TB_PESSOAS 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.PES_COD IS NULL) THEN NEW.PES_COD = GEN_ID(GEN_PESSOAS_COD,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_PROCED_CARGA FOR TB_PROCEDIMENTOS_CARGA 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.PROC_COD IS NULL) THEN NEW.PROC_COD = GEN_ID(GEN_TB_PROCED_CARGA_ID,1);

END ^

CREATE TRIGGER TG_GERA_CODIGO_PROCED_RESULT FOR TB_PROCEDIMENTOS_RESULTADO 
ACTIVE BEFORE INSERT POSITION 0 
AS 
BEGIN 
IF (NEW.PROR_COD IS NULL) THEN NEW.PROR_COD = GEN_ID(gen_tb_proced_resultado_id,1);

END ^

CREATE TRIGGER CHECK_1 FOR TB_UF 
ACTIVE AFTER UPDATE POSITION 1 
 ^

COMMIT WORK ^
SET TERM ; ^

/* Grant permissions for this database */
GRANT DELETE, SELECT ON IBE$LOG_BLOB_FIELDS TO TRIGGER IBE$LOG_TABLES_BD;
GRANT DELETE, SELECT ON IBE$LOG_FIELDS TO TRIGGER IBE$LOG_TABLES_BD;
GRANT DELETE, SELECT ON IBE$LOG_KEYS TO TRIGGER IBE$LOG_TABLES_BD;
GRANT UPDATE, REFERENCES ON IBE$LOG_TABLES TO TRIGGER IBE$LOG_TABLES_BD;
GRANT INSERT ON IBE$VERSION_HISTORY TO TRIGGER IBE$VERSION_HISTORY_BI;
GRANT SELECT ON TB_ALELOS TO PROCEDURE BU_ALELOS;
GRANT INSERT ON TB_CONTAALELO TO PROCEDURE BU_ALELOS;
