-- ============================================================================
-- MIGRATION: Add Qwen Classification Columns to Communications Table
-- ============================================================================
-- Date: 2026-10-02
-- Purpose: Add confidence score, reasoning, and extraction timestamp for Qwen AI classifications
-- Idempotent: Safe to run multiple times using INFORMATION_SCHEMA checks

-- Use the newipcsistemas database
USE `novos_sistemas_ipc`;

-- ============================================================================
-- HELPER: Add confidence column if it doesn't exist
-- ============================================================================
DELIMITER //

DROP PROCEDURE IF EXISTS add_confidence_column //

CREATE PROCEDURE add_confidence_column()
BEGIN
  DECLARE col_exists INT DEFAULT 0;

  SELECT COUNT(*) INTO col_exists
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'novos_sistemas_ipc'
  AND TABLE_NAME = 'communications'
  AND COLUMN_NAME = 'confidence';

  IF col_exists = 0 THEN
    ALTER TABLE `communications`
    ADD COLUMN `confidence` FLOAT NULL DEFAULT NULL
    COMMENT 'Classification confidence score from Qwen (0.0-1.0)';
    SELECT 'Column confidence added successfully' AS status;
  ELSE
    SELECT 'Column confidence already exists, skipping' AS status;
  END IF;
END //

-- ============================================================================
-- HELPER: Add reasoning column if it doesn't exist
-- ============================================================================

DROP PROCEDURE IF EXISTS add_reasoning_column //

CREATE PROCEDURE add_reasoning_column()
BEGIN
  DECLARE col_exists INT DEFAULT 0;

  SELECT COUNT(*) INTO col_exists
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'novos_sistemas_ipc'
  AND TABLE_NAME = 'communications'
  AND COLUMN_NAME = 'reasoning';

  IF col_exists = 0 THEN
    ALTER TABLE `communications`
    ADD COLUMN `reasoning` TEXT NULL DEFAULT NULL
    COMMENT 'Justification for classification provided by Qwen';
    SELECT 'Column reasoning added successfully' AS status;
  ELSE
    SELECT 'Column reasoning already exists, skipping' AS status;
  END IF;
END //

-- ============================================================================
-- HELPER: Add extracted_at column if it doesn't exist
-- ============================================================================

DROP PROCEDURE IF EXISTS add_extracted_at_column //

CREATE PROCEDURE add_extracted_at_column()
BEGIN
  DECLARE col_exists INT DEFAULT 0;

  SELECT COUNT(*) INTO col_exists
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'novos_sistemas_ipc'
  AND TABLE_NAME = 'communications'
  AND COLUMN_NAME = 'extracted_at';

  IF col_exists = 0 THEN
    ALTER TABLE `communications`
    ADD COLUMN `extracted_at` TIMESTAMP NULL DEFAULT NULL
    COMMENT 'When the classification was extracted/generated by Qwen';
    SELECT 'Column extracted_at added successfully' AS status;
  ELSE
    SELECT 'Column extracted_at already exists, skipping' AS status;
  END IF;
END //

-- ============================================================================
-- HELPER: Create index on confidence if it doesn't exist
-- ============================================================================

DROP PROCEDURE IF EXISTS add_confidence_index //

CREATE PROCEDURE add_confidence_index()
BEGIN
  DECLARE idx_exists INT DEFAULT 0;

  SELECT COUNT(*) INTO idx_exists
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = 'novos_sistemas_ipc'
  AND TABLE_NAME = 'communications'
  AND INDEX_NAME = 'idx_confidence';

  IF idx_exists = 0 THEN
    CREATE INDEX `idx_confidence` ON `communications` (`confidence`);
    SELECT 'Index idx_confidence created successfully' AS status;
  ELSE
    SELECT 'Index idx_confidence already exists, skipping' AS status;
  END IF;
END //

DELIMITER ;

-- ============================================================================
-- EXECUTE PROCEDURES
-- ============================================================================

CALL add_confidence_column();
CALL add_reasoning_column();
CALL add_extracted_at_column();
CALL add_confidence_index();

-- ============================================================================
-- CLEANUP: Drop helper procedures
-- ============================================================================

DROP PROCEDURE IF EXISTS add_confidence_column;
DROP PROCEDURE IF EXISTS add_reasoning_column;
DROP PROCEDURE IF EXISTS add_extracted_at_column;
DROP PROCEDURE IF EXISTS add_confidence_index;

-- ============================================================================
-- DONE
-- ============================================================================
-- Migration completed successfully. All Qwen classification columns have been
-- added to the communications table in a safe, idempotent manner.
