
unit ufDM;

interface

uses
  SysUtils, Classes, DB, ADODB, IniFiles, Dialogs, Forms;

type
  TDM = class(TDataModule)
    ADOC_SCPG: TADOConnection;
    qRestricao: TADOQuery;
    qHosts: TADOQuery;
    qLocalColeta: TADOQuery;
    qCasos: TADOQuery;
    qVara: TADOQuery;
    qItem: TADOQuery;
    qUF: TADOQuery;
    qParametros: TADOQuery;
    qMaxProcesso: TADOQuery;
    qHistorico: TADOQuery;
    DS_Historico: TDataSource;
    qRegras: TADOQuery;
    qParcelamento: TADOQuery;
    qMaxComarca: TADOQuery;
    qUFUF_SIGLA: TStringField;
    qUFUF_DESC: TStringField;
    qParcelamentoPRO_COD: TIntegerField;
    qParcelamentoPAR_NPARC: TIntegerField;
    qParcelamentoPAR_VLR: TBCDField;
    qParcelamentoPAR_DATA: TDateField;
    qParcelamentoPAR_SIT: TIntegerField;
    qItemITE_COD: TIntegerField;
    qItemITE_DESC: TStringField;
    qMaxComarcaMAX: TIntegerField;
    qMaxProcessoMAX: TIntegerField;
    qCasosCAS_CONTR: TIntegerField;
    qCasosCAS_CODIGO: TStringField;
    qCasosCAS_DESC: TStringField;
    qCasosCAS_VLR: TBCDField;
    qCasosCAS_NOME0: TStringField;
    qCasosCAS_NOME1: TStringField;
    qCasosCAS_NOME2: TStringField;
    qCasosCAS_NOME3: TStringField;
    qCasosCAS_NOME4: TStringField;
    qCasosCAS_SIG1: TStringField;
    qCasosCAS_SIG2: TStringField;
    qCasosCAS_SIG3: TStringField;
    qCasosCAS_SIG4: TStringField;
    qHistoricoHIS_CONTR: TIntegerField;
    qHistoricoPRO_COD: TIntegerField;
    qHistoricoITE_COD: TIntegerField;
    qHistoricoHIS_DATA: TDateField;
    qHistoricoHIS_OBS: TStringField;
    qParametrosPAM_COD: TIntegerField;
    qParametrosPAM_UNID: TStringField;
    qRegrasREG_COD: TIntegerField;
    qRegrasREG_MOD: TStringField;
    qRegrasITE_COD: TIntegerField;
    qRegrasREG_TIPO: TIntegerField;
    qRegrasREG_PASTA: TStringField;
    qRegrasREG_CPNOM: TStringField;
    qRegrasDescricaoItem: TStringField;
    qRestricaoRES_COD: TIntegerField;
    qRestricaoRES_DESC: TStringField;
    qJuiz: TADOQuery;
    qJuizJUI_COD: TIntegerField;
    qJuizJUI_DESC: TStringField;
    qJuizJUI_SEXO: TStringField;
    qPessoas: TADOQuery;
    DS_Pessoas: TDataSource;
    qPessoasPRO_COD: TIntegerField;
    qPessoasPES_COD: TIntegerField;
    qPessoasPES_NOME: TStringField;
    qPessoasPES_SIT: TIntegerField;
    qPessoasPES_DTNAS: TDateField;
    qPessoasPES_LCNAS: TStringField;
    qPessoasPES_SEXO: TStringField;
    qMaxPessoa: TADOQuery;
    qMaxPessoaMAX: TIntegerField;
    qHistoricoDescricaodoItem: TStringField;
    qMaxHistorico: TADOQuery;
    qMaxHistoricoMAX: TIntegerField;
    DS_Juiz: TDataSource;
    qMaxVara: TADOQuery;
    qMaxVaraMAX: TIntegerField;
    DS_UF: TDataSource;
    qComarca: TADOQuery;
    qComarcaCOM_COD: TIntegerField;
    qComarcaCOM_DESC: TStringField;
    qComarcaCOM_SIGLA: TStringField;
    qComarcaUF_SIGLA: TStringField;
    qComarcaDESCRICAOESTADO: TStringField;
    DS_Comarca: TDataSource;
    qDadosProcesso: TADOQuery;
    qDadosProcessoDPR_COD: TIntegerField;
    qDadosProcessoDPR_TIA: TStringField;
    qDadosProcessoREQTE: TStringField;
    qDadosProcessoREQDO: TStringField;
    qDadosProcessoPRO_COD: TIntegerField;
    DS_DadosProcesso: TDataSource;
    qMaxDadosProcesso: TADOQuery;
    qMaxDadosProcessoMAX: TIntegerField;
    qItemITE_ORG: TStringField;
    qParametrosPAM_DDEST: TStringField;
    qParametrosPAM_DRCOL: TStringField;
    qParametrosPAM_DPADR: TStringField;
    qKits: TADOQuery;
    DS_Kits: TDataSource;
    qKitsKIT_COD: TIntegerField;
    qKitsKIT_TIP: TIntegerField;
    qKitsKIT_NUM: TIntegerField;
    qKitsCOL_COD: TIntegerField;
    qKitsKIT_DENV: TDateField;
    qKitsKIT_DRET: TDateField;
    qKitsKIT_CEXA: TIntegerField;
    qColetador: TADOQuery;
    qColetadorCOL_COD: TIntegerField;
    qColetadorCOL_ORDEM: TIntegerField;
    qColetadorCOL_NOME: TStringField;
    DS_Coletador: TDataSource;
    qKitsKIT_STATUS: TStringField;
    qParcelamentoPAR_TPPG: TStringField;
    qParcelamentoCONTROLE: TIntegerField;
    qParcelamentoPAR_OBS: TStringField;
    qPessoasPES_NDOC: TStringField;
    qPessoasPES_TDOC: TStringField;
    qPesquisa: TADOQuery;
    ds_Pesquisa: TDataSource;
    qPesquisaPEQ_COD: TIntegerField;
    qPesquisaPEQ_NOME: TStringField;
    qPesquisaPEQ_NDOC: TStringField;
    qPesquisaPEQ_ESTC: TStringField;
    qPesquisaPEQ_DTNAS: TDateField;
    qPesquisaPEQ_LCNAS: TStringField;
    qPesquisaPEQ_LCRE: TStringField;
    qPesquisaPEQ_FONE: TStringField;
    qParametrosPAM_DPADRDG: TStringField;
    qParametrosPAM_DREXCEL: TStringField;
    qMaxLocalColeta: TADOQuery;
    qMaxLocalColetaMAX: TIntegerField;
    qEnderecos: TADOQuery;
    qEnderecosEND_COD: TIntegerField;
    qEnderecosEND_LOC: TStringField;
    qEnderecosEND_NMR: TStringField;
    qEnderecosEND_BAI: TStringField;
    qEnderecosEND_END: TStringField;
    qEnderecosEND_CID: TStringField;
    qEnderecosEND_CEP: TStringField;
    qEnderecosUF_SIGLA: TStringField;
    DS_Enderecos: TDataSource;
    qCorrespondencia: TADOQuery;
    qCorrespondenciaEND_COD: TIntegerField;
    qCorrespondenciaPRO_COD: TIntegerField;
    qCorrespondenciaLkp_LocalCorrespondencia: TStringField;
    qCorrespondenciaOBS: TStringField;
    qCorrespondenciaTIPO: TStringField;
    qCorrespondenciaREGCORREIO: TStringField;
    qPessoasPES_INICIAIS: TStringField;
    qMapa_ExtAmpli: TADOQuery;
    qExtracao: TADOQuery;
    DS_Extracao: TDataSource;
    DS_Mapa_ExtAmpli: TDataSource;
    qParametrosPAM_DIRMPEXTRACAO: TStringField;
    qVaraVAR_SIGLA: TStringField;
    qVaraVAR_COD: TIntegerField;
    qVaraVAR_DESC: TStringField;
    qVaraJUI_COD: TIntegerField;
    qVaraJUI_DESC: TStringField;
    qVaraCOM_COD: TIntegerField;
    qVaraNOMECOMARCA: TStringField;
    qVaraDESCRICAOESTADO: TStringField;
    qVaraUF_SIGLA: TStringField;
    qMapa_ExtAmpliPRO_COD: TIntegerField;
    qMapa_ExtAmpliMPEA_DATA: TDateField;
    qMapa_ExtAmpliMPEA_LOTE: TIntegerField;
    qMapa_ExtAmpliMPEA_ORD: TIntegerField;
    qMapa_ExtAmpliPES_INICIAIS: TStringField;
    qMapa_ExtAmpliSIT_SIGLA: TStringField;
    qParametrosPAM_DIRMPEXTRACAOXLS: TStringField;
    qCorrespondenciaCORR_DATA: TDateField;
    qCorrespondenciaCORR_USU: TStringField;
    qLocalColetaLCO_COD: TIntegerField;
    qLocalColetaLCO_NOME: TStringField;
    qLocalColetaLCO_SEXO: TIntegerField;
    qLocalColetaLCO_CRM: TStringField;
    qLocalColetaLCO_LABT: TStringField;
    qLocalColetaLCO_FONE: TStringField;
    qLocalColetaLCO_END: TStringField;
    qLocalColetaLCO_CID: TStringField;
    qLocalColetaUF_SIGLA: TStringField;
    qLocalColetaLCO_TLIE: TIntegerField;
    qLocalColetaLCO_CATE: TIntegerField;
    qLocalColetaLCO_TRAT: TIntegerField;
    qLocalColetaLCO_CEL: TStringField;
    qLocalColetaLCO_RES: TStringField;
    qLocalColetaLCO_EMAIL: TStringField;
    qLocalColetaLCO_SITE: TStringField;
    qLocalColetaLCO_CEP: TStringField;
    qLocalColetaLCO_DTRE: TDateField;
    qLocalColetaLCO_DCAD: TDateField;
    qLocalColetaDescricaoEstado: TStringField;
    qKitsLkpColetador: TStringField;
    qHostsHOS_NOME: TStringField;
    qHostsHOS_USUA: TStringField;
    qHostsHOS_SENHA: TStringField;
    qHostsRES_COD: TIntegerField;
    qHostsHOS_MAQUI: TStringField;
    qHostsDescRestricao: TStringField;
    qImpressoes: TADOQuery;
    DS_Impressoes: TDataSource;
    qImpressoesPRO_COD: TIntegerField;
    qImpressoesITE_COD: TIntegerField;
    qImpressoesIMP_TIPO: TStringField;
    qImpressoesIMP_QDFL: TIntegerField;
    qImpressoesIMP_QDIM: TIntegerField;
    qImpressoesIMP_IMPR: TStringField;
    qImpressoesIMP_DATA: TDateField;
    qImpressoesIMP_CONTR: TIntegerField;
    qEnderecosEND_TRATA: TStringField;
    DS_LocalColeta: TDataSource;
    qPessoasGrid: TADOQuery;
    DS_PessoasGrid: TDataSource;
    qPessoasGridPRO_COD: TIntegerField;
    qPessoasGridPES_COD: TIntegerField;
    qPessoasGridPES_NOME: TStringField;
    qPessoasGridPES_INICIAIS: TStringField;
    qPessoasGridPES_SIT: TIntegerField;
    qPessoasGridPES_DTNAS: TDateField;
    qPessoasGridPES_LCNAS: TStringField;
    qPessoasGridPES_SEXO: TStringField;
    qPessoasGridPES_TDOC: TStringField;
    qPessoasGridPES_NDOC: TStringField;
    qPessoasGridSIT_COD: TIntegerField;
    qPessoasGridSIT_NM: TStringField;
    qPessoasGridSIT_SIGLA: TStringField;
    qPessoasGridSIT_ORDEM: TIntegerField;
    qContaAlelo: TADOQuery;
    qContaAleloQTD_CODIGO: TIntegerField;
    qColetadoresRelatorios: TADOQuery;
    DSColetadoresRelatorios: TDataSource;
    qColetadoresRelatoriosCODIGO: TIntegerField;
    qColetadoresRelatoriosORDEM: TIntegerField;
    qColetadoresRelatoriosNOME: TStringField;
    qColetadoresKits: TADOQuery;
    DSColetadoresKits: TDataSource;
    qColetadoresKitsCOL_COD: TIntegerField;
    qColetadoresKitsCOL_ORDEM: TIntegerField;
    qColetadoresKitsCOL_NOME: TStringField;
    qLocalColetaLCO_NUMCARTCORREIO: TIntegerField;
    qCreditos: TADOQuery;
    DS_Creditos: TDataSource;
    qCreditosID_CREDITO: TIntegerField;
    qCreditosJUI_COD: TIntegerField;
    qCreditosPRO_COD: TIntegerField;
    qCreditosCRE_DATA: TDateField;
    qCreditosPRO_DTREC: TDateField;
    qCreditosCRED_QDCRE: TStringField;
    qJuizJUI_CREDITO: TStringField;
    qCreditos_Temporario: TADOQuery;
    ds_Creditos_Temporario: TDataSource;
    qCreditos_TemporarioID_CREDITO: TIntegerField;
    qCreditos_TemporarioJUI_COD: TIntegerField;
    qCreditos_TemporarioPRO_COD: TIntegerField;
    qCreditos_TemporarioCRED_QDCRE: TStringField;
    qCreditos_TemporarioCRE_DATA: TDateField;
    qCreditos_TemporarioPRO_DTREC: TDateField;
    qCompraKits: TADOQuery;
    qCompraKitsNUMERO_KIT: TIntegerField;
    qCompraKitsNOME_SUPAI: TStringField;
    qCompraKitsCPF_SUPAI: TStringField;
    qCompraKitsENDE_SUPAI: TStringField;
    qCompraKitsDATA_CADASTRO: TDateField;
    qCasoEndereco: TADOQuery;
    qCasoEnderecoCOR_COD: TIntegerField;
    qCasoEnderecoCOR_DESTINO: TStringField;
    qCasoEnderecoCOR_END: TStringField;
    qCasoEnderecoCOR_BAIRRO: TStringField;
    qCasoEnderecoCOR_CID: TStringField;
    qCasoEnderecoCOR_CEP: TStringField;
    qCasoEnderecoUF_SIGLA: TStringField;
    qCasoEnderecoPRO_COD: TIntegerField;
    qMaxCasoEndereco: TADOQuery;
    qMaxCasoEnderecoULTIMO: TIntegerField;
    qVaraENDE_VARA: TStringField;
    qVaraBAIRRO_VARA: TStringField;
    qVaraCIDADE_VARA: TStringField;
    qVaraCEP_VARA: TStringField;
    qLocalColetaLCO_SITUACAO: TStringField;
    qLocalColetaLCO_DNASC: TDateField;
    DS_ExtracaoCasos: TDataSource;
    qExtracaoCasos: TADOQuery;
    qExtracaoCasosEXTC_COD: TIntegerField;
    qExtracaoCasosSUP_DATA: TDateField;
    qExtracaoCasosSUP_SUPER: TStringField;
    qExtracaoCasosSUP_MEIOREM: TIntegerField;
    qExtracaoCasosSUP_PESPARA: TStringField;
    qExtracaoCasosSUP_SIMGEAMO: TIntegerField;
    qExtracaoCasosSUP_INCLMACRI: TIntegerField;
    qExtracaoCasosSUP_INCLMASUP: TIntegerField;
    qExtracaoCasosANA_DTLEIT: TDateField;
    qExtracaoCasosANA_RESCONF: TStringField;
    qExtracaoCasosPRO_COD: TIntegerField;
    qExtracaoCasosANA_INICONFNCONF: TIntegerField;
    qExtracaoCasosANA_SIMGEAMO: TIntegerField;
    qExtracaoCasosANA_INCLMACRI: TIntegerField;
    qExtracaoCasosANA_INCLMASUP: TIntegerField;
    qExtracaoCasosANA_INCLUSAO: TIntegerField;
    qExtracaoCasosANA_MUTACAO: TIntegerField;
    qExtracaoCasosANA_MARCADOR: TStringField;
    qExtracaoCasosANA_EXCLUSAO: TIntegerField;
    qExtracaoCasosANA_CONTRAPROVA: TIntegerField;
    qExtracaoCasosANA_CONFORME: TIntegerField;
    qExtracaoCasosANA_REPETICAO: TIntegerField;
    qExtracaoCasosANA_REPETICAOM: TIntegerField;
    qExtracaoCasosANA_REPETICAOC: TIntegerField;
    qExtracaoCasosANA_REPETICAOSP: TIntegerField;
    qExtracaoCasosANA_OUANADP18: TIntegerField;
    qExtracaoCasosANA_OUANACROY: TIntegerField;
    qExtracaoCasosANA_OUANARESP: TStringField;
    qExtracaoCasosANA_INCLUSIVO: TIntegerField;
    qExtracaoCasosANA_OUANADATA: TDateField;
    qExtracaoCasosANA_LADCOMPALE: TIntegerField;
    qExtracaoCasosANA_CONTRDNA: TIntegerField;
    qExtracaoEXT_COD: TIntegerField;
    qExtracaoEXT_DATA: TDateField;
    qExtracaoMPEA_LOTE: TIntegerField;
    qExtracaoEXT_RESP: TStringField;
    qExtracaoEXT_SUPER: TStringField;
    qExtracaoSEQ_DTCORR: TDateField;
    qExtracaoSEQ_RESP: TStringField;
    qExtracaoSEQ_SUPER: TStringField;
    qExtracaoSEQ_FORLOTE: TStringField;
    qExtracaoSEQ_ILSLOTE: TStringField;
    qExtracaoSEQ_LADLOTE: TStringField;
    qExtracaoSEQ_PIP10UL: TIntegerField;
    qExtracaoSEQ_PIP200UL: TIntegerField;
    qExtracaoSEQ_PIP1000UL: TIntegerField;
    qExtracaoREA_FTALOTE: TStringField;
    qExtracaoREA_CHELEXLOTE: TStringField;
    qExtracaoREA_AGUALOTE: TStringField;
    qExtracaoAMPL_RESP: TStringField;
    qExtracaoAMPL_SUPER: TStringField;
    qExtracaoAMPL_DATA: TDateField;
    qExtracaoAMPL_KITLOTE: TStringField;
    qExtracaoAMPL_TERM9700: TIntegerField;
    qExtracaoAMPL_TERM2720: TIntegerField;
    qExtracaoAMPL_PIP10UL: TIntegerField;
    qExtracaoAMPL_PIP200UL: TIntegerField;
    qExtracaoAMPL_PIP1000UL: TIntegerField;
    qExtracaoEQU_OUTROS: TStringField;
    qExtracaoEQU_BLCTER19: TIntegerField;
    qExtracaoEQU_BLCTER20: TIntegerField;
    qExtracaoEQU_VORTEX18: TIntegerField;
    qExtracaoEQU_AGIMAG25: TIntegerField;
    qExtracaoEQU_BOMBVA30: TIntegerField;
    qExtracaoEQU_CENTR31: TIntegerField;
    qExtracaoEQU_PIP10UL: TIntegerField;
    qExtracaoEQU_PIP200UL: TIntegerField;
    qExtracaoEQU_PIP1000UL: TIntegerField;
    qExtracaoEQU_PIP10ULNUM: TIntegerField;
    qExtracaoEQU_PIP200ULNUM: TIntegerField;
    qExtracaoEQU_PIP1000ULNUM: TIntegerField;
    qExtracaoCasosMPEA_LOTE: TIntegerField;
    qLocalColetaLCO_BANCO: TStringField;
    qLocalColetaLCO_AGENCIA: TStringField;
    qLocalColetaLCO_CONTA: TStringField;
    qLocalColetaLCO_CPFCNPJ: TStringField;
    qParametrosPAM_VLRJUD: TBCDField;
    qParametrosPAM_VLREXTRA: TBCDField;
    qParametrosPAM_VLRMP: TBCDField;
    qParametrosPAM_VLRDP: TBCDField;
    qParametrosPAM_VLRCT: TBCDField;
    qParametrosPAM_DRPDF: TStringField;
    qConsultaLocaisColeta: TADOQuery;
    qConsultaLocaisColetaLCO_COD: TIntegerField;
    qConsultaLocaisColetaLCO_NOME: TStringField;
    qConsultaLocaisColetaLCO_SEXO: TIntegerField;
    qConsultaLocaisColetaLCO_CRM: TStringField;
    qConsultaLocaisColetaLCO_LABT: TStringField;
    qConsultaLocaisColetaLCO_FONE: TStringField;
    qConsultaLocaisColetaLCO_END: TStringField;
    qConsultaLocaisColetaLCO_CID: TStringField;
    qConsultaLocaisColetaUF_SIGLA: TStringField;
    qConsultaLocaisColetaLCO_TLIE: TIntegerField;
    qConsultaLocaisColetaLCO_CATE: TIntegerField;
    qConsultaLocaisColetaLCO_TRAT: TIntegerField;
    qConsultaLocaisColetaLCO_CEL: TStringField;
    qConsultaLocaisColetaLCO_RES: TStringField;
    qConsultaLocaisColetaLCO_EMAIL: TStringField;
    qConsultaLocaisColetaLCO_SITE: TStringField;
    qConsultaLocaisColetaLCO_CEP: TStringField;
    qConsultaLocaisColetaLCO_DTRE: TDateField;
    qConsultaLocaisColetaLCO_DCAD: TDateField;
    qConsultaLocaisColetaLCO_NUMCARTCORREIO: TIntegerField;
    qConsultaLocaisColetaLCO_SITUACAO: TStringField;
    qConsultaLocaisColetaLCO_DNASC: TDateField;
    qConsultaLocaisColetaLCO_CPFCNPJ: TStringField;
    qConsultaLocaisColetaLCO_BANCO: TStringField;
    qConsultaLocaisColetaLCO_AGENCIA: TStringField;
    qConsultaLocaisColetaLCO_CONTA: TStringField;
    qLocalColetaLCO_MINKIT: TIntegerField;
    qParcelamentoPAR_HORA: TTimeField;
    qHostsHOS_SITUACAO: TIntegerField;
    qHostsHOS_DTULTALT: TDateField;
    qMapa_ExtAmpli_Casos: TADOQuery;
    DS_Mapa_ExtAmpli_Casos: TDataSource;
    qMapa_ExtAmpli_CasosMPEA_LOTE: TIntegerField;
    qMapa_ExtAmpli_CasosPRO_COD: TIntegerField;
    qMapa_ExtAmpli_CasosMPEA_ORD: TIntegerField;
    qMapa_ExtAmpli_CasosPES_INICIAIS: TStringField;
    qMapa_ExtAmpli_CasosSIT_SIGLA: TStringField;
    qColaborador: TADOQuery;
    dsColaborador: TDataSource;
    qColaboradorCLB_COD: TIntegerField;
    qColaboradorCLB_PIS: TStringField;
    qColaboradorCLB_NOME: TStringField;
    qParametrosPAM_IMPETQ: TIntegerField;
    qParametrosPAM_DIRDOC: TStringField;
    qCreditosCRED_INICIAL: TIntegerField;
    qCreditosCRED_FINAL: TIntegerField;
    qMaxCreditos: TADOQuery;
    qMaxCreditosULTIMO: TIntegerField;
    qRelCreditos: TADOQuery;
    qRelCreditosID_CREDITO: TIntegerField;
    qRelCreditosJUI_COD: TIntegerField;
    qRelCreditosPRO_COD: TIntegerField;
    qRelCreditosCRED_QDCRE: TStringField;
    qRelCreditosCRE_DATA: TDateField;
    qRelCreditosPRO_DTREC: TDateField;
    qRelCreditosCRED_INICIAL: TIntegerField;
    qRelCreditosCRED_FINAL: TIntegerField;
    ds_RelCreditos: TDataSource;
    qMaxJuiz: TADOQuery;
    qMaxJuizULTIMO: TIntegerField;
    qBanco: TADOQuery;
    ds_Banco: TDataSource;
    qBancoCOD_BANCO: TStringField;
    qBancoDESC_BANCO: TStringField;
    qLocalColetaLCO_PIX: TStringField;
    qParcelamentoPAR_ONDE: TStringField;
    qParcelamentoPAR_DATAPREVISTA: TDateField;
    qParcelamentoPAR_NMFOR: TStringField;
    qParametrosPAM_DIRINTEGRADOC: TStringField;
    qHistoricoHIS_DOC: TStringField;
    qParametrosPAM_DIRINTEGRAOF: TStringField;
    qCalcCred_BuscaProcessos: TADOQuery;
    qCalcCred_BuscaProcessosPRO_COD: TIntegerField;
    qCalcCred_BuscaProcessosPRO_ANO: TIntegerField;
    qCalcCred_BuscaProcessosPRO_NPERC: TStringField;
    qCalcCred_BuscaProcessosPRO_TIPO: TIntegerField;
    qCalcCred_BuscaProcessosPRO_AUTO: TStringField;
    qCalcCred_BuscaProcessosUF_SIGLA: TStringField;
    qCalcCred_BuscaProcessosCAS_CODIGO: TStringField;
    qCalcCred_BuscaProcessosCOM_COD: TIntegerField;
    qCalcCred_BuscaProcessosVAR_COD: TIntegerField;
    qCalcCred_BuscaProcessosLCO_COD: TIntegerField;
    qCalcCred_BuscaProcessosPRO_HCOLE: TStringField;
    qCalcCred_BuscaProcessosPRO_DCOLE: TDateField;
    qCalcCred_BuscaProcessosPRO_HREC: TStringField;
    qCalcCred_BuscaProcessosPRO_DREC: TDateField;
    qCalcCred_BuscaProcessosPRO_DRESU: TDateField;
    qCalcCred_BuscaProcessosPRO_SIT: TIntegerField;
    qCalcCred_BuscaProcessosPRO_NCOMP: TIntegerField;
    qCalcCred_BuscaProcessosPRO_RESUL: TIntegerField;
    qCalcCred_BuscaProcessosPRO_PROB: TStringField;
    qCalcCred_BuscaProcessosPRO_ARETI: TStringField;
    qCalcCred_BuscaProcessosJUI_COD: TIntegerField;
    qCalcCred_BuscaProcessosFG_PROP: TStringField;
    qCalcCred_BuscaProcessosPRO_USUCAD: TStringField;
    qCalcCred_BuscaProcessosPRO_NUMLAUDO: TStringField;
    qCalcCred_BuscaProcessosPRO_RASTREAR: TStringField;
    qCalcCred_BuscaProcessosPRO_CARREGACREDITO: TStringField;
    qCalcCred_BuscaProcessosPRO_CREDITODNA: TStringField;
    qCalcCred_BuscaProcessosPRO_HTREC: TStringField;
    qCalcCred_BuscaProcessosPRO_LACRE: TStringField;
    qCalcCred_BuscaProcessosPRO_FG_EXTERNO: TIntegerField;
    qCalcCred_BuscaProcessosPRO_FG_RESUL: TIntegerField;
    qCalcCred_BuscaProcessosPRO_DATA_EXTERNO: TDateField;
    qCalcCred_BuscaProcessosFG_CALCCRED: TIntegerField;
    qCalcCred_Insere: TADOQuery;
    qCalcCred_InserePRO_COD: TIntegerField;
    qCalcCred_InsereUF_SIGLA: TStringField;
    qCalcCred_InsereCOM_COD: TIntegerField;
    qCalcCred_InsereVAR_COD: TIntegerField;
    qCalcCred_InsereNUM_CREDITO: TIntegerField;
    qCalcCred_InsereDAT_CREDITO: TDateField;
    qCalcCred_GeraCredito: TADOQuery;
    qCalcCred_GeraCreditoUF_SIGLA: TStringField;
    qCalcCred_GeraCreditoCOM_COD: TIntegerField;
    qCalcCred_GeraCreditoVAR_COD: TIntegerField;
    qCalcCred_GeraCreditoCOUNT: TIntegerField;
    qCalcCred_AjustaProcesso: TADOQuery;
    qCalcCred_AtualizaCred: TADOQuery;
    qCalcCred_AtualizaCredPRO_COD: TIntegerField;
    qParametrosPAM_ULTCRED: TIntegerField;
    procedure qParcelamentoPAR_SITGetText(Sender: TField; var Text: String;
      DisplayText: Boolean);
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DM: TDM;

implementation

uses ufProcesso;


{$R *.dfm}

procedure TDM.qParcelamentoPAR_SITGetText(Sender: TField; var Text: String;
  DisplayText: Boolean);
begin
	Case qParcelamentoPAR_SIT.AsInteger of
        1 : Text := 'OK';
        2 : Text := 'DEVOLVIDO';
        3 : Text := 'NÃO FORNECIDO';
    end;
end;

procedure TDM.DataModuleCreate(Sender: TObject);
var
Arquivo: TIniFile;
CaminhoBanco, Caminho, StringConexao : String;
begin
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Caminho := ExtractFilePath(Application.ExeName)+'SCPG.ini';
Arquivo := TIniFile.Create(Caminho);
Try
with ADOC_SCPG do
begin
 CaminhoBanco     := Arquivo.ReadString('DADOS','DATABASE','');
 StringConexao    := 'DRIVER=Firebird/InterBase(r) driver;UID=SYSDBA;PWD=masterkey;DBNAME=' + CaminhoBanco + ';';
 Connected        := False;
 ConnectionString := StringConexao;
 Connected        := True;
 Arquivo.Free;

 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 ////////////////////////////////////////////////////////////////////////////////////////////////////
end;
Except
ShowMessage('Não foi possivel conectar! Nenhum servidor disponível...');
End;
////////////////////////////////////////////////////////////////////////////////////////////////////
end;

end.
