object fRelCapa2: TfRelCapa2
  Left = 171
  Top = 61
  Caption = 'Relat'#243'rio da Capa'
  ClientHeight = 632
  ClientWidth = 1264
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Scaled = False
  TextHeight = 13
  object QuickRep1: TRLReport
    Tag = 1
    Left = 8
    Top = 16
    Width = 1123
    Height = 794
    Margins.LeftMargin = 50.000000000000000000
    DataSource = fProcessos.ds_ParcelasCapa
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    PageSetup.Orientation = poLandscape
    object QRBand3: TRLBand
      Left = 189
      Top = 38
      Width = 896
      Height = 521
      BandType = btTitle
      object QRDBText13: TRLDBText
        Left = 458
        Top = 11
        Width = 435
        Height = 75
        Alignment = taRightJustify
        DataField = 'PRO_NPERC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -67
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText14: TRLDBText
        Left = 127
        Top = 208
        Width = 110
        Height = 22
        DataField = 'VAR_DESC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText15: TRLDBText
        Left = 193
        Top = 181
        Width = 114
        Height = 22
        DataField = 'COM_DESC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText16: TRLDBText
        Left = 703
        Top = 89
        Width = 190
        Height = 32
        Alignment = taRightJustify
        DataField = 'CAS_CODIGO'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -27
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText17: TRLDBText
        Left = 180
        Top = 345
        Width = 103
        Height = 18
        DataField = 'PRO_DCOLE'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText18: TRLDBText
        Left = 150
        Top = 244
        Width = 112
        Height = 22
        DataField = 'LCO_NOME'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText19: TRLDBText
        Left = 196
        Top = 280
        Width = 64
        Height = 15
        DataField = 'LCO_CATE'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText20: TRLDBText
        Left = 241
        Top = 374
        Width = 93
        Height = 18
        DataField = 'PRO_DREC'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRLabel29: TRLLabel
        Left = 87
        Top = 247
        Width = 60
        Height = 21
        Caption = 'Coletador:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel32: TRLLabel
        Left = 86
        Top = 278
        Width = 106
        Height = 21
        Caption = 'Tipo do Coletador:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel33: TRLLabel
        Left = 86
        Top = 347
        Width = 91
        Height = 17
        Caption = 'Data da Coleta:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel34: TRLLabel
        Left = 85
        Top = 375
        Width = 154
        Height = 17
        Caption = 'Data e Hora da Recep'#231#227'o:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel35: TRLLabel
        Left = 87
        Top = 191
        Width = 36
        Height = 21
        Caption = 'Local:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel36: TRLLabel
        Left = 475
        Top = 385
        Width = 128
        Height = 17
        Caption = 'Data Limite do Laudo:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object DataLimite: TRLLabel
        Left = 499
        Top = 407
        Width = 78
        Height = 19
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel38: TRLLabel
        Left = 86
        Top = 402
        Width = 101
        Height = 21
        Caption = 'Quem cadastrou:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object Cadastrador: TRLLabel
        Left = 191
        Top = 402
        Width = 71
        Height = 21
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel40: TRLLabel
        Left = 88
        Top = 501
        Width = 86
        Height = 17
        Caption = 'Valores Pagos'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object CRIANCA: TRLLabel
        Left = 142
        Top = 304
        Width = 116
        Height = 33
        Caption = 'Crianca'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -27
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel42: TRLLabel
        Left = 87
        Top = 311
        Width = 49
        Height = 17
        Caption = 'Crian'#231'a:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel43: TRLLabel
        Left = 140
        Top = 471
        Width = 121
        Height = 28
        Caption = 'INCLUS'#195'O'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel44: TRLLabel
        Left = 360
        Top = 472
        Width = 129
        Height = 28
        Caption = 'EXCLUS'#195'O'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel45: TRLLabel
        Left = 707
        Top = 472
        Width = 180
        Height = 28
        Caption = 'INCONCLUSIVO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object Hora: TRLLabel
        Left = 343
        Top = 375
        Width = 26
        Height = 19
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object Minuto: TRLLabel
        Left = 377
        Top = 375
        Width = 24
        Height = 19
        AutoSize = False
        Caption = 'MINUTO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel48: TRLLabel
        Left = 177
        Top = 181
        Width = 6
        Height = 21
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel49: TRLLabel
        Left = 333
        Top = 375
        Width = 6
        Height = 19
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel50: TRLLabel
        Left = 274
        Top = 345
        Width = 6
        Height = 19
        Caption = '-'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object HORACOL: TRLLabel
        Left = 287
        Top = 345
        Width = 25
        Height = 19
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object MINUTOCOL: TRLLabel
        Left = 323
        Top = 345
        Width = 24
        Height = 19
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel53: TRLLabel
        Left = 359
        Top = 420
        Width = 40
        Height = 17
        Caption = 'rubrica'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel54: TRLLabel
        Left = 310
        Top = 345
        Width = 9
        Height = 19
        Caption = 'h'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel55: TRLLabel
        Left = 345
        Top = 345
        Width = 26
        Height = 19
        Caption = 'min'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel56: TRLLabel
        Left = 398
        Top = 375
        Width = 26
        Height = 19
        Caption = 'min'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel57: TRLLabel
        Left = 365
        Top = 375
        Width = 9
        Height = 19
        Caption = 'h'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel58: TRLLabel
        Left = 583
        Top = 161
        Width = 106
        Height = 21
        Caption = 'OBSERVA'#199#213'ES:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object NumLaudo: TRLLabel
        Left = 108
        Top = 77
        Width = 132
        Height = 33
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -27
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel60: TRLLabel
        Left = 583
        Top = 161
        Width = 106
        Height = 17
        Caption = 'OBSERVA'#199#213'ES:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel61: TRLLabel
        Left = 617
        Top = 365
        Width = 138
        Height = 21
        Caption = 'Envio: ____ / _____ / 20 ___'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel62: TRLLabel
        Left = 617
        Top = 389
        Width = 88
        Height = 14
        Caption = 'Meio: (    ) E-MAIL'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel63: TRLLabel
        Left = 645
        Top = 409
        Width = 88
        Height = 17
        Caption = '(    ) PROTOCOLO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object ESTADO: TRLLabel
        Left = 128
        Top = 180
        Width = 45
        Height = 23
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel65: TRLLabel
        Left = 386
        Top = 161
        Width = 161
        Height = 19
        Caption = 'NOTA FICAL: ___________'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel66: TRLLabel
        Left = 384
        Top = 215
        Width = 77
        Height = 19
        Caption = 'DIGITAL: (   )'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel67: TRLLabel
        Left = 645
        Top = 429
        Width = 120
        Height = 17
        Caption = '(    ) CORREIO ________'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel68: TRLLabel
        Left = 645
        Top = 450
        Width = 154
        Height = 17
        Caption = '(    ) PROTOCOLO ELETR'#212'NICO'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel69: TRLLabel
        Left = 762
        Top = 498
        Width = 123
        Height = 18
        Caption = 'ESCANEADO: (   )'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRDBText1: TRLDBText
        Left = 129
        Top = 141
        Width = 111
        Height = 22
        DataField = 'PRO_AUTO'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRLabel1: TRLLabel
        Left = 87
        Top = 143
        Width = 39
        Height = 21
        Caption = 'Autos:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
      object QRLabel2: TRLLabel
        Left = 586
        Top = 503
        Width = 71
        Height = 15
        Caption = 'Cr'#233'dito-DNA:'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = False
      end
      object QRDBText2: TRLDBText
        Left = 659
        Top = 503
        Width = 98
        Height = 15
        AutoSize = False
        DataField = 'PRO_CREDITODNA'
        DataSource = fProcessos.ds_GeraCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object BarraCodigo: TRLBarcode
        Left = 115
        Top = 37
        Width = 117
        Height = 34
        Margins.LeftMargin = 1.000000000000000000
        Margins.RightMargin = 1.000000000000000000
        Alignment = taCenter
        BarcodeType = bcCode128A
      end
      object RLLabel1: TRLLabel
        Left = 544
        Top = 215
        Width = 139
        Height = 16
        Caption = 'CERTIFICADO: ______'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Transparent = False
      end
    end
    object QRBand4: TRLBand
      Left = 189
      Top = 559
      Width = 896
      Height = 20
      object QRDBText21: TRLDBText
        Left = 216
        Top = 1
        Width = 51
        Height = 14
        Alignment = taRightJustify
        DataField = 'PAR_VLR'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText22: TRLDBText
        Left = 291
        Top = 1
        Width = 56
        Height = 14
        DataField = 'PAR_TPPG'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText23: TRLDBText
        Left = 587
        Top = 1
        Width = 278
        Height = 15
        AutoSize = False
        DataField = 'PAR_OBS'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
      object QRDBText24: TRLDBText
        Left = 88
        Top = 1
        Width = 60
        Height = 14
        Alignment = taCenter
        DataField = 'PAR_DATA'
        DataSource = fProcessos.ds_ParcelasCapa
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        Text = ''
        Transparent = False
      end
    end
  end
end
